// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE
FROM devices
WHERE platform = $1
  AND push_token = $2
`

type DeleteDeviceByTokenParams struct {
	Platform  string
	PushToken string
}

func (q *Queries) DeleteDeviceByToken(ctx context.Context, arg DeleteDeviceByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, arg.Platform, arg.PushToken)
	return err
}

const deleteUserDeviceByToken = `-- name: DeleteUserDeviceByToken :exec
DELETE
FROM devices
WHERE user_id = $1
  AND platform = $2
  AND push_token = $3
`

type DeleteUserDeviceByTokenParams struct {
	UserID    uuid.UUID
	Platform  string
	PushToken string
}

func (q *Queries) DeleteUserDeviceByToken(ctx context.Context, arg DeleteUserDeviceByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceByToken, arg.UserID, arg.Platform, arg.PushToken)
	return err
}

const listHouseholdDevices = `-- name: ListHouseholdDevices :many
SELECT d.id, d.user_id, d.platform, d.push_token, d.apns_environment, d.last_seen_at
FROM devices d
         JOIN memberships m ON m.user_id = d.user_id
WHERE m.household_id = $1
  AND d.platform = $2
ORDER BY d.last_seen_at DESC
`

type ListHouseholdDevicesParams struct {
	HouseholdID uuid.UUID
	Platform    string
}

func (q *Queries) ListHouseholdDevices(ctx context.Context, arg ListHouseholdDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listHouseholdDevices, arg.HouseholdID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PushToken,
			&i.ApnsEnvironment,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, platform, push_token, apns_environment, last_seen_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (platform, push_token) DO UPDATE
    SET user_id          = EXCLUDED.user_id,
        apns_environment = EXCLUDED.apns_environment,
        last_seen_at     = EXCLUDED.last_seen_at
`

type UpsertDeviceParams struct {
	UserID          uuid.UUID
	Platform        string
	PushToken       string
	ApnsEnvironment *string
	LastSeenAt      time.Time
}

// A token already registered, to anyone, moves to this user.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice,
		arg.UserID,
		arg.Platform,
		arg.PushToken,
		arg.ApnsEnvironment,
		arg.LastSeenAt,
	)
	return err
}
