// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const deleteAnonymousDevicesUnseenSince = `-- name: DeleteAnonymousDevicesUnseenSince :execrows
DELETE
FROM devices
WHERE user_id IS NULL
  AND last_seen_at < $1
`

func (q *Queries) DeleteAnonymousDevicesUnseenSince(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnonymousDevicesUnseenSince, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE
FROM devices
WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE
FROM devices
WHERE platform = $1
  AND push_token = $2
`

type DeleteDeviceByTokenParams struct {
	Platform  string
	PushToken string
}

func (q *Queries) DeleteDeviceByToken(ctx context.Context, arg DeleteDeviceByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, arg.Platform, arg.PushToken)
	return err
}

const deleteUserDeviceByToken = `-- name: DeleteUserDeviceByToken :exec
DELETE
FROM devices
WHERE user_id = $1
  AND platform = $2
  AND push_token = $3
  AND promotions_consented_at IS NULL
`

type DeleteUserDeviceByTokenParams struct {
	UserID    *uuid.UUID
	Platform  string
	PushToken string
}

func (q *Queries) DeleteUserDeviceByToken(ctx context.Context, arg DeleteUserDeviceByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceByToken, arg.UserID, arg.Platform, arg.PushToken)
	return err
}

const detachConsentingUserDeviceByToken = `-- name: DetachConsentingUserDeviceByToken :exec
UPDATE devices
SET user_id = NULL
WHERE user_id = $1
  AND platform = $2
  AND push_token = $3
  AND promotions_consented_at IS NOT NULL
`

type DetachConsentingUserDeviceByTokenParams struct {
	UserID    *uuid.UUID
	Platform  string
	PushToken string
}

func (q *Queries) DetachConsentingUserDeviceByToken(ctx context.Context, arg DetachConsentingUserDeviceByTokenParams) error {
	_, err := q.db.Exec(ctx, detachConsentingUserDeviceByToken, arg.UserID, arg.Platform, arg.PushToken)
	return err
}

const findDeviceByTokenForUpdate = `-- name: FindDeviceByTokenForUpdate :one
SELECT id, user_id, platform, push_token, apns_environment, language, promotions_consented_at, completion_notices, last_seen_at
FROM devices
WHERE platform = $1
  AND push_token = $2
    FOR UPDATE
`

type FindDeviceByTokenForUpdateParams struct {
	Platform  string
	PushToken string
}

func (q *Queries) FindDeviceByTokenForUpdate(ctx context.Context, arg FindDeviceByTokenForUpdateParams) (Device, error) {
	row := q.db.QueryRow(ctx, findDeviceByTokenForUpdate, arg.Platform, arg.PushToken)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.ApnsEnvironment,
		&i.Language,
		&i.PromotionsConsentedAt,
		&i.CompletionNotices,
		&i.LastSeenAt,
	)
	return i, err
}

const insertPromotionsConsentChange = `-- name: InsertPromotionsConsentChange :exec
INSERT INTO promotions_consent_changes (device_id, user_id, consented, changed_at)
VALUES ($1, $2, $3, $4)
`

type InsertPromotionsConsentChangeParams struct {
	DeviceID  uuid.UUID
	UserID    *uuid.UUID
	Consented bool
	ChangedAt time.Time
}

func (q *Queries) InsertPromotionsConsentChange(ctx context.Context, arg InsertPromotionsConsentChangeParams) error {
	_, err := q.db.Exec(ctx, insertPromotionsConsentChange,
		arg.DeviceID,
		arg.UserID,
		arg.Consented,
		arg.ChangedAt,
	)
	return err
}

const listHouseholdDevices = `-- name: ListHouseholdDevices :many
SELECT d.id, d.user_id, d.platform, d.push_token, d.apns_environment, d.language, d.promotions_consented_at, d.completion_notices, d.last_seen_at
FROM devices d
         JOIN memberships m ON m.user_id = d.user_id
WHERE m.household_id = $1
  AND d.platform = $2
ORDER BY d.last_seen_at DESC
`

type ListHouseholdDevicesParams struct {
	HouseholdID uuid.UUID
	Platform    string
}

func (q *Queries) ListHouseholdDevices(ctx context.Context, arg ListHouseholdDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listHouseholdDevices, arg.HouseholdID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PushToken,
			&i.ApnsEnvironment,
			&i.Language,
			&i.PromotionsConsentedAt,
			&i.CompletionNotices,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, platform, push_token, apns_environment, language, promotions_consented_at,
                     completion_notices, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6,
        COALESCE($7::boolean, true), $8)
ON CONFLICT (platform, push_token) DO UPDATE
    SET user_id                 = COALESCE(EXCLUDED.user_id, devices.user_id),
        apns_environment        = EXCLUDED.apns_environment,
        language                = EXCLUDED.language,
        completion_notices      = COALESCE($7::boolean, devices.completion_notices),
        promotions_consented_at = CASE
                                      WHEN EXCLUDED.promotions_consented_at IS NOT NULL
                                          THEN COALESCE(devices.promotions_consented_at,
                                                        EXCLUDED.promotions_consented_at)
            END,
        last_seen_at            = EXCLUDED.last_seen_at
RETURNING id
`

type UpsertDeviceParams struct {
	UserID                *uuid.UUID
	Platform              string
	PushToken             string
	ApnsEnvironment       *string
	Language              string
	PromotionsConsentedAt *time.Time
	CompletionNotices     *bool
	LastSeenAt            time.Time
}

// A token already registered moves to this user; an anonymous registration
// (no user) leaves its owner in place. Consenting again keeps the original time.
// A NULL completion_notices keeps the device's setting.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.Platform,
		arg.PushToken,
		arg.ApnsEnvironment,
		arg.Language,
		arg.PromotionsConsentedAt,
		arg.CompletionNotices,
		arg.LastSeenAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
