// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"uuid"
)

type Device struct {
	ID                    uuid.UUID
	UserID                *uuid.UUID
	Platform              string
	PushToken             string
	ApnsEnvironment       *string
	Language              string
	PromotionsConsentedAt *time.Time
	CompletionNotices     bool
	LastSeenAt            time.Time
}
