// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"uuid"
)

type Device struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Platform        string
	PushToken       string
	ApnsEnvironment *string
	LastSeenAt      time.Time
}
