package catalog

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

const header = "Generated by tools/analytics/catalog from shared/analytics/catalog.yaml. Do not edit."

type enum struct {
	name   string
	values []string
}

func (c Catalog) enums(platform string) []enum {
	return []enum{
		{"AnalyticsEvent", namesOn(c.Events, platform)},
		{"AnalyticsParameter", parametersOn(c.Parameters, platform)},
		{"AnalyticsUserProperty", namesOn(c.UserProperties, platform)},
		{"AnalyticsScreen", namesOn(c.Screens, platform)},
		{"ScreenEntry", namesOn(c.Entries, platform)},
	}
}

func (c Catalog) Swift() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n", header)
	for _, e := range c.enums(PlatformIOS) {
		fmt.Fprintf(&b, "\nnonisolated enum %s: String {\n", e.name)
		for _, value := range e.values {
			name := swiftCase(value)
			if name == value {
				fmt.Fprintf(&b, "    case %s\n", name)
			} else {
				fmt.Fprintf(&b, "    case %s = %q\n", name, value)
			}
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

func (c Catalog) Kotlin(pkg string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\npackage %s\n", header, pkg)
	for _, e := range c.enums(PlatformAndroid) {
		fmt.Fprintf(&b, "\nenum class %s(val key: String) {\n", e.name)
		for _, value := range e.values {
			fmt.Fprintf(&b, "    %s(%q),\n", strings.ToUpper(value), value)
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

type ga4Metric struct {
	Name string `json:"name"`
	Unit string `json:"unit"`
}

type ga4Definitions struct {
	Comment         string      `json:"comment"`
	UserDimensions  []string    `json:"user_dimensions"`
	EventDimensions []string    `json:"event_dimensions"`
	Metrics         []ga4Metric `json:"metrics"`
}

func (c Catalog) GA4() ([]byte, error) {
	definitions := ga4Definitions{Comment: header, EventDimensions: []string{}, Metrics: []ga4Metric{}}
	for _, p := range c.UserProperties {
		definitions.UserDimensions = append(definitions.UserDimensions, p.Name)
	}
	for _, p := range c.Parameters {
		switch p.GA4 {
		case "dimension":
			definitions.EventDimensions = append(definitions.EventDimensions, p.Name)
		case "metric":
			definitions.Metrics = append(definitions.Metrics, ga4Metric{Name: p.Name, Unit: p.unit()})
		}
	}
	data, err := json.MarshalIndent(definitions, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode ga4 definitions: %w", err)
	}
	return append(data, '\n'), nil
}

func (c Catalog) SQL() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "-- %s\n", header)
	b.WriteString(`-- One row per exported event, with the parameters the apps send as columns.
SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  TIMESTAMP_MICROS(event_timestamp) AS event_time,
  event_name,
  -- The app was on screen. Reminders, RevenueCat's rc_* events, and Firebase's automatic ones also come in while it
  -- is closed, so these four are what counts a user as active.
  event_name IN ('session_start', 'user_engagement', 'screen_view', 'daily_state') AS foreground,
  user_pseudo_id,
  platform,
  device.mobile_brand_name AS device_brand,
  app_info.version AS app_version,
  geo.country AS country,
  device.language AS language,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'firebase_screen') AS screen,
`)
	for _, p := range c.UserProperties {
		fmt.Fprintf(&b, "  (SELECT value.string_value FROM UNNEST(user_properties) WHERE key = '%s') AS user_%s,\n",
			p.Name, p.Name)
	}
	for _, p := range c.Parameters {
		switch p.Type {
		case "string":
			fmt.Fprintf(&b, "  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = '%s') AS %s,\n",
				p.Name, p.column())
		case "int":
			fmt.Fprintf(&b, "  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = '%s') AS %s,\n",
				p.Name, p.column())
		case "number":
			b.WriteString("  (\n    SELECT COALESCE(value.double_value, value.float_value, CAST(value.int_value AS FLOAT64))\n")
			fmt.Fprintf(&b, "    FROM UNNEST(event_params) WHERE key = '%s'\n  ) AS %s,\n", p.Name, p.column())
		}
	}
	b.WriteString("  event_value_in_usd\nFROM `__PROJECT__.__SOURCE__.events_*`\n" +
		"-- Streaming export adds events_intraday_* tables that repeat days already in the daily tables.\n" +
		"WHERE _TABLE_SUFFIX NOT LIKE 'intraday%'\n")
	return b.Bytes()
}

func swiftCase(snake string) string {
	parts := strings.Split(snake, "_")
	for i := 1; i < len(parts); i++ {
		switch parts[i] {
		case "id", "url":
			parts[i] = strings.ToUpper(parts[i])
		default:
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
