// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name)
VALUES ($1)
RETURNING id, display_name, created_at
`

func (q *Queries) CreateUser(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var i User
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const createUserIdentity = `-- name: CreateUserIdentity :exec
INSERT INTO user_identities (user_id, provider, subject)
VALUES ($1, $2, $3)
`

type CreateUserIdentityParams struct {
	UserID   uuid.UUID
	Provider string
	Subject  string
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error {
	_, err := q.db.Exec(ctx, createUserIdentity, arg.UserID, arg.Provider, arg.Subject)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE
FROM refresh_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshTokenFamily = `-- name: DeleteRefreshTokenFamily :exec
DELETE
FROM refresh_tokens
WHERE family_id = $1
`

func (q *Queries) DeleteRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenFamily, familyID)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppleToken = `-- name: GetAppleToken :one
SELECT refresh_token_ciphertext, client
FROM apple_tokens
WHERE user_id = $1
`

type GetAppleTokenRow struct {
	RefreshTokenCiphertext []byte
	Client                 string
}

func (q *Queries) GetAppleToken(ctx context.Context, userID uuid.UUID) (GetAppleTokenRow, error) {
	row := q.db.QueryRow(ctx, getAppleToken, userID)
	var i GetAppleTokenRow
	err := row.Scan(&i.RefreshTokenCiphertext, &i.Client)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, expires_at, used_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenByHashRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.display_name, u.created_at
FROM users u
         JOIN user_identities i ON i.user_id = u.id
WHERE i.provider = $1
  AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const upsertAppleToken = `-- name: UpsertAppleToken :exec
INSERT INTO apple_tokens (user_id, refresh_token_ciphertext, client)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET refresh_token_ciphertext = excluded.refresh_token_ciphertext,
        client                   = excluded.client,
        updated_at               = now()
`

type UpsertAppleTokenParams struct {
	UserID                 uuid.UUID
	RefreshTokenCiphertext []byte
	Client                 string
}

func (q *Queries) UpsertAppleToken(ctx context.Context, arg UpsertAppleTokenParams) error {
	_, err := q.db.Exec(ctx, upsertAppleToken, arg.UserID, arg.RefreshTokenCiphertext, arg.Client)
	return err
}

const useRefreshToken = `-- name: UseRefreshToken :one
UPDATE refresh_tokens
SET used_at = $1
WHERE token_hash = $2
  AND used_at IS NULL
RETURNING id, user_id, family_id, expires_at, used_at
`

type UseRefreshTokenParams struct {
	UsedAt    *time.Time
	TokenHash []byte
}

type UseRefreshTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) UseRefreshToken(ctx context.Context, arg UseRefreshTokenParams) (UseRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, useRefreshToken, arg.UsedAt, arg.TokenHash)
	var i UseRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
