// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}
