// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"
	"time"
	"uuid"

	"github.com/mickamy/LocateDo/internal/feature/household/model"
	categoryv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/category/v1"
	householdv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/household/v1"
	placev1 "github.com/mickamy/LocateDo/internal/gen/locatedo/place/v1"
	todov1 "github.com/mickamy/LocateDo/internal/gen/locatedo/todo/v1"
	"github.com/mickamy/LocateDo/internal/lib/converters"
)

// ContentsFromCreateHouseholdRequest maps *householdv1.CreateHouseholdRequest to model.Contents.
func ContentsFromCreateHouseholdRequest(src *householdv1.CreateHouseholdRequest) (model.Contents, error) {
	if src == nil {
		return model.Contents{}, nil
	}
	var v0 []model.ImportCategory
	if v1 := src.GetCategories(); v1 != nil {
		v0 = make([]model.ImportCategory, len(v1))
		for i2, e3 := range v1 {
			v5, err4 := ImportCategoryFromCategoryInput(e3)
			if err4 != nil {
				return model.Contents{}, fmt.Errorf("map model.Contents.Categories: %w", err4)
			}
			v0[i2] = v5
		}
	}
	var v6 []model.ImportPlace
	if v7 := src.GetPlaces(); v7 != nil {
		v6 = make([]model.ImportPlace, len(v7))
		for i8, e9 := range v7 {
			v11, err10 := ImportPlaceFromPlaceInput(e9)
			if err10 != nil {
				return model.Contents{}, fmt.Errorf("map model.Contents.Places: %w", err10)
			}
			v6[i8] = v11
		}
	}
	var v12 []model.InitialTodo
	if v13 := src.GetTodos(); v13 != nil {
		v12 = make([]model.InitialTodo, len(v13))
		for i14, e15 := range v13 {
			v17, err16 := InitialTodoFromHouseholdv1(e15)
			if err16 != nil {
				return model.Contents{}, fmt.Errorf("map model.Contents.Todos: %w", err16)
			}
			v12[i14] = v17
		}
	}
	return model.Contents{
		Categories: v0,
		Places:     v6,
		Todos:      v12,
	}, nil
}

// ImportCategoryFromCategoryInput maps *categoryv1.CategoryInput to model.ImportCategory.
func ImportCategoryFromCategoryInput(src *categoryv1.CategoryInput) (model.ImportCategory, error) {
	if src == nil {
		return model.ImportCategory{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.ImportCategory{}, fmt.Errorf("map model.ImportCategory.ID: %w", err0)
	}
	return model.ImportCategory{
		ID:         v1,
		BuiltinKey: BuiltinCategoryToKey(src.GetBuiltin()),
		Name:       src.Name,
		Icon:       src.GetIcon(),
		Color:      src.GetColor(),
		SortOrder:  src.GetSortOrder(),
	}, nil
}

// ImportPlaceFromPlaceInput maps *placev1.PlaceInput to model.ImportPlace.
func ImportPlaceFromPlaceInput(src *placev1.PlaceInput) (model.ImportPlace, error) {
	if src == nil {
		return model.ImportPlace{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.ImportPlace{}, fmt.Errorf("map model.ImportPlace.ID: %w", err0)
	}
	var v2 *uuid.UUID
	if v3 := src.CategoryId; v3 != nil {
		var v4 uuid.UUID
		v6, err5 := uuid.Parse(*v3)
		if err5 != nil {
			return model.ImportPlace{}, fmt.Errorf("map model.ImportPlace.CategoryID: %w", err5)
		}
		v4 = v6
		v2 = &v4
	}
	return model.ImportPlace{
		ID:         v1,
		Name:       src.GetName(),
		Lat:        src.GetLat(),
		Lng:        src.GetLng(),
		RadiusM:    src.GetRadiusM(),
		CategoryID: v2,
		SortOrder:  src.GetSortOrder(),
	}, nil
}

// InitialTodoFromHouseholdv1 maps *householdv1.InitialTodo to model.InitialTodo.
func InitialTodoFromHouseholdv1(src *householdv1.InitialTodo) (model.InitialTodo, error) {
	if src == nil {
		return model.InitialTodo{}, nil
	}
	v1, err0 := ImportTodoFromTodoInput(src.GetTodo())
	if err0 != nil {
		return model.InitialTodo{}, fmt.Errorf("map model.InitialTodo.Todo: %w", err0)
	}
	var v2 *time.Time
	if v3 := src.GetCompletedAt(); v3 != nil {
		v4 := converters.TimestampToTime(v3)
		v2 = &v4
	}
	return model.InitialTodo{
		Todo:        v1,
		CompletedAt: v2,
	}, nil
}

// ImportTodoFromTodoInput maps *todov1.TodoInput to model.ImportTodo.
func ImportTodoFromTodoInput(src *todov1.TodoInput) (model.ImportTodo, error) {
	if src == nil {
		return model.ImportTodo{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.ImportTodo{}, fmt.Errorf("map model.ImportTodo.ID: %w", err0)
	}
	v3, err2 := uuid.Parse(src.GetPlaceId())
	if err2 != nil {
		return model.ImportTodo{}, fmt.Errorf("map model.ImportTodo.PlaceID: %w", err2)
	}
	var v4 *uuid.UUID
	if v5 := src.AssigneeId; v5 != nil {
		var v6 uuid.UUID
		v8, err7 := uuid.Parse(*v5)
		if err7 != nil {
			return model.ImportTodo{}, fmt.Errorf("map model.ImportTodo.AssigneeID: %w", err7)
		}
		v6 = v8
		v4 = &v6
	}
	return model.ImportTodo{
		ID:         v1,
		PlaceID:    v3,
		Title:      src.GetTitle(),
		AssigneeID: v4,
	}, nil
}

// HouseholdToHouseholdv1 maps model.Household to *householdv1.Household.
func HouseholdToHouseholdv1(src model.Household) *householdv1.Household {
	return &householdv1.Household{
		Id:      converters.UUIDToString(src.ID),
		OwnerId: converters.UUIDToString(src.OwnerID),
		Plan:    PlanToHouseholdv1(src.Plan),
	}
}
