// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	repository2 "github.com/mickamy/LocateDo/internal/feature/household/repository"
	"github.com/mickamy/LocateDo/internal/feature/todo/repository"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewDeleteTodo initializes dependencies and constructs DeleteTodo.
func NewDeleteTodo(infra di.Infra) *DeleteTodo {
	transactor := infra.Transactor
	reader := infra.Reader
	todos := repository.NewTodo(reader)

	return &DeleteTodo{
		transactor: transactor,
		todos:      todos,
	}
}

// NewPutTodo initializes dependencies and constructs PutTodo.
func NewPutTodo(infra di.Infra) *PutTodo {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository2.NewHousehold(reader)
	todos := repository.NewTodo(reader)

	return &PutTodo{
		transactor: transactor,
		households: households,
		todos:      todos,
	}
}

// NewSetTodoCompletion initializes dependencies and constructs SetTodoCompletion.
func NewSetTodoCompletion(infra di.Infra) *SetTodoCompletion {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository2.NewHousehold(reader)
	memberships := repository2.NewMembership(reader)
	todos := repository.NewTodo(reader)
	messages := outbox.NewRepository(reader)

	return &SetTodoCompletion{
		transactor:  transactor,
		households:  households,
		memberships: memberships,
		todos:       todos,
		messages:    messages,
	}
}
