// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/category/usecase"
)

// NewCategory initializes dependencies and constructs Category.
func NewCategory(infra di.Infra) *Category {
	putCategory := usecase.NewPutCategory(infra)
	deleteCategory := usecase.NewDeleteCategory(infra)

	return &Category{
		putCategory:    putCategory,
		deleteCategory: deleteCategory,
	}
}
