version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /server/tools
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tools/l10n
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directories:
      - /ios
      - /android
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: opentofu
    directories:
      - /deploy/tofu/bootstrap
      - /deploy/tofu/google
      - /deploy/tofu/persistent
      - /deploy/tofu/prod
    schedule:
      interval: weekly
