version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /server/tools
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tools/l10n
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
