// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_queries.sql

package queries

import (
	"context"

	"uuid"
)

const deleteCategory = `-- name: DeleteCategory :exec
DELETE
FROM categories
WHERE id = $1
  AND household_id = $2
`

type DeleteCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.HouseholdID)
	return err
}

const upsertCategory = `-- name: UpsertCategory :exec
INSERT INTO categories (id, household_id, builtin_key, name, icon, color, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id, household_id) DO UPDATE
    SET builtin_key = EXCLUDED.builtin_key,
        name        = EXCLUDED.name,
        icon        = EXCLUDED.icon,
        color       = EXCLUDED.color,
        sort_order  = EXCLUDED.sort_order
`

type UpsertCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BuiltinKey  *string
	Name        *string
	Icon        string
	Color       string
	SortOrder   int32
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCategory,
		arg.ID,
		arg.HouseholdID,
		arg.BuiltinKey,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.SortOrder,
	)
	return err
}
