// Code generated by kanna. DO NOT EDIT.

package worker

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/outbox"
	"github.com/mickamy/LocateDo/internal/worker/job"
)

// NewWorker initializes dependencies and constructs Worker.
func NewWorker(infra di.Infra, lib di.Lib) *Worker {
	transactor := infra.Transactor
	reader := infra.Reader
	repository := outbox.NewRepository(reader)
	pushHousehold := job.NewPushHousehold(infra)
	revokeAppleToken := job.NewRevokeAppleToken(infra, lib)
	syncEntitlement := job.NewSyncEntitlement(infra)
	sendCampaign := job.NewSendCampaign(infra)
	handlers := NewHandlers(pushHousehold, revokeAppleToken, syncEntitlement, sendCampaign)
	consumer := NewConsumer(transactor, repository, handlers)
	sweepTombstones := job.NewSweepTombstones(infra)
	sweepRefreshTokens := job.NewSweepRefreshTokens(infra)
	sweepDeadMessages := job.NewSweepDeadMessages(infra)
	sweepAnonymousDevices := job.NewSweepAnonymousDevices(infra)
	reconcileEntitlements := job.NewReconcileEntitlements(infra)
	reportOutbox := job.NewReportOutbox(infra)
	tasks := NewTasks(sweepTombstones, sweepRefreshTokens, sweepDeadMessages, sweepAnonymousDevices, reconcileEntitlements, reportOutbox)
	scheduler := NewScheduler(tasks)

	return &Worker{
		Consumer:  consumer,
		Scheduler: scheduler,
	}
}
