// Code generated by kanna. DO NOT EDIT.

package worker

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/outbox"
	"github.com/mickamy/LocateDo/internal/worker/job"
)

// NewWorker initializes dependencies and constructs Worker.
func NewWorker(infra di.Infra, lib di.Lib) *Worker {
	transactor := infra.Transactor
	reader := infra.Reader
	repository := outbox.NewRepository(reader)
	revokeAppleToken := job.NewRevokeAppleToken(infra, lib)
	handlers := NewHandlers(revokeAppleToken)
	consumer := NewConsumer(transactor, repository, handlers)
	sweepTombstones := job.NewSweepTombstones(infra)
	sweepRefreshTokens := job.NewSweepRefreshTokens(infra)
	sweepDeadMessages := job.NewSweepDeadMessages(infra)
	tasks := NewTasks(sweepTombstones, sweepRefreshTokens, sweepDeadMessages)
	scheduler := NewScheduler(tasks)

	return &Worker{
		Consumer:  consumer,
		Scheduler: scheduler,
	}
}
