// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/device/repository"
)

// NewRegisterDevice initializes dependencies and constructs RegisterDevice.
func NewRegisterDevice(infra di.Infra) *RegisterDevice {
	transactor := infra.Transactor
	reader := infra.Reader
	devices := repository.NewDevice(reader)

	return &RegisterDevice{
		transactor: transactor,
		devices:    devices,
	}
}
