// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const countAudience = `-- name: CountAudience :many
SELECT platform, count(*) AS devices
FROM devices
WHERE language = $1
  AND promotions_consented_at IS NOT NULL
GROUP BY platform
`

type CountAudienceRow struct {
	Platform string
	Devices  int64
}

func (q *Queries) CountAudience(ctx context.Context, language string) ([]CountAudienceRow, error) {
	rows, err := q.db.Query(ctx, countAudience, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAudienceRow
	for rows.Next() {
		var i CountAudienceRow
		if err := rows.Scan(&i.Platform, &i.Devices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnsent = `-- name: CountUnsent :one
SELECT count(*)
FROM campaigns
WHERE language = $1
  AND sent_at IS NULL
`

func (q *Queries) CountUnsent(ctx context.Context, language string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsent, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findLastSentAt = `-- name: FindLastSentAt :one
SELECT sent_at
FROM campaigns
WHERE language = $1
  AND sent_at IS NOT NULL
ORDER BY sent_at DESC
LIMIT 1
`

func (q *Queries) FindLastSentAt(ctx context.Context, language string) (*time.Time, error) {
	row := q.db.QueryRow(ctx, findLastSentAt, language)
	var sent_at *time.Time
	err := row.Scan(&sent_at)
	return sent_at, err
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO campaigns (language, title, body, url, target_count, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertCampaignParams struct {
	Language    string
	Title       string
	Body        string
	Url         *string
	TargetCount int32
	CreatedAt   time.Time
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCampaign,
		arg.Language,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.TargetCount,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
