// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/campaign/repository"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewSendCampaign initializes dependencies and constructs SendCampaign.
func NewSendCampaign(infra di.Infra) *SendCampaign {
	transactor := infra.Transactor
	reader := infra.Reader
	campaigns := repository.NewCampaign(reader)
	messages := outbox.NewRepository(reader)

	return &SendCampaign{
		transactor: transactor,
		campaigns:  campaigns,
		messages:   messages,
	}
}
