// Code generated by kanna. DO NOT EDIT.

package messages

import (
	"golang.org/x/text/language"

	"github.com/go-kanna/kanna/i18n"
)

// CompletionNoticeMany returns the "completion_notice.many" message.
func CompletionNoticeMany(name string, title string, others int) i18n.Message {
	return i18n.Message{Key: "completion_notice.many", Args: []i18n.Arg{
		{Name: "name", Value: name},
		{Name: "title", Value: title},
		{Name: "others", Value: others},
	}}
}

// CompletionNoticeOne returns the "completion_notice.one" message.
func CompletionNoticeOne(name string, title string) i18n.Message {
	return i18n.Message{Key: "completion_notice.one", Args: []i18n.Arg{
		{Name: "name", Value: name},
		{Name: "title", Value: title},
	}}
}

// CompletionNoticeSomeone returns the "completion_notice.someone" message.
func CompletionNoticeSomeone() i18n.Message {
	return i18n.Message{Key: "completion_notice.someone"}
}

// Localizer renders this package's messages in the compiled locale best
// matching tag. Messages missing from the matched locale fall back to the
// default language.
func Localizer(tag language.Tag) i18n.Localizer {
	return bundle.Localizer(tag)
}

// bundle holds every locale this package was generated from.
var bundle = i18n.NewBundle("en",
	i18n.Catalog{Lang: "en", Entries: map[string]i18n.Entry{
		"completion_notice.many":    {Single: i18n.Template{{Param: "name"}, {Text: " checked off \""}, {Param: "title"}, {Text: "\" and "}, {Param: "others", Kind: i18n.KindInt}, {Text: " more"}}},
		"completion_notice.one":     {Single: i18n.Template{{Param: "name"}, {Text: " checked off \""}, {Param: "title"}, {Text: "\""}}},
		"completion_notice.someone": {Single: i18n.Template{{Text: "Someone in your household"}}},
	}},
	i18n.Catalog{Lang: "ja", Entries: map[string]i18n.Entry{
		"completion_notice.many":    {Single: i18n.Template{{Param: "name"}, {Text: "が「"}, {Param: "title"}, {Text: "」ほか "}, {Param: "others", Kind: i18n.KindInt}, {Text: " 件を完了しました"}}},
		"completion_notice.one":     {Single: i18n.Template{{Param: "name"}, {Text: "が「"}, {Param: "title"}, {Text: "」を完了しました"}}},
		"completion_notice.someone": {Single: i18n.Template{{Text: "家族"}}},
	}},
)
