// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"github.com/mickamy/LocateDo/internal/feature/device/model"
	devicev1 "github.com/mickamy/LocateDo/internal/gen/locatedo/device/v1"
)

// DeviceFromRegisterDeviceRequest maps *devicev1.RegisterDeviceRequest to model.Device.
func DeviceFromRegisterDeviceRequest(src *devicev1.RegisterDeviceRequest) model.Device {
	if src == nil {
		return model.Device{}
	}
	return model.Device{
		Platform:  PlatformFromDevicev1(src.GetPlatform()),
		PushToken: src.GetPushToken(),
	}
}
