// Code generated by kanna. DO NOT EDIT.

package auth

import (
	"github.com/mickamy/LocateDo/internal/di"
)

// NewAppleAndroid initializes dependencies and constructs AppleAndroid.
func NewAppleAndroid(config di.Config) *AppleAndroid {
	cfg := config.Apple

	return &AppleAndroid{
		cfg: cfg,
	}
}
