// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/place/usecase"
)

// NewPlace initializes dependencies and constructs Place.
func NewPlace(infra di.Infra) *Place {
	putPlace := usecase.NewPutPlace(infra)
	deletePlace := usecase.NewDeletePlace(infra)

	return &Place{
		putPlace:    putPlace,
		deletePlace: deletePlace,
	}
}
