// Code generated by kanna. DO NOT EDIT.

package fixture

import (
	"uuid"

	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/LocateDo/internal/feature/category/model"
)

func Category(setters ...func(m *model.Category)) model.Category {
	m := model.Category{
		ID:          uuid.MustParse(gofakeit.UUID()),
		HouseholdID: uuid.MustParse(gofakeit.UUID()),
		Icon:        gofakeit.Word(),
		Color:       gofakeit.Word(),
		SortOrder:   gofakeit.Int32(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}
