// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/usecase"
)

// NewAccount initializes dependencies and constructs Account.
func NewAccount(infra di.Infra, lib di.Lib) *Account {
	signInWithApple := usecase.NewSignInWithApple(infra, lib)
	refreshToken := usecase.NewRefreshToken(infra, lib)
	deleteAccount := usecase.NewDeleteAccount(infra)

	return &Account{
		signInWithApple: signInWithApple,
		refreshToken:    refreshToken,
		deleteAccount:   deleteAccount,
	}
}
