// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/usecase"
)

// NewAccount initializes dependencies and constructs Account.
func NewAccount(infra di.Infra, lib di.Lib) *Account {
	signInWithApple := usecase.NewSignInWithApple(infra, lib)
	signInWithGoogle := usecase.NewSignInWithGoogle(infra, lib)
	refreshToken := usecase.NewRefreshToken(infra, lib)
	signOut := usecase.NewSignOut(infra)
	deleteAccount := usecase.NewDeleteAccount(infra)
	syncEntitlement := usecase.NewSyncEntitlement(infra)

	return &Account{
		signInWithApple:  signInWithApple,
		signInWithGoogle: signInWithGoogle,
		refreshToken:     refreshToken,
		signOut:          signOut,
		deleteAccount:    deleteAccount,
		syncEntitlement:  syncEntitlement,
	}
}
