// Code generated by kanna. DO NOT EDIT.

package webhook

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewRevenueCat initializes dependencies and constructs RevenueCat.
func NewRevenueCat(config di.Config, infra di.Infra) *RevenueCat {
	cfg := config.RevenueCat
	transactor := infra.Transactor
	reader := infra.Reader
	messages := outbox.NewRepository(reader)

	return &RevenueCat{
		cfg:        cfg,
		transactor: transactor,
		messages:   messages,
	}
}
