// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/household/repository"
	repository2 "github.com/mickamy/LocateDo/internal/feature/place/repository"
)

// NewDeletePlace initializes dependencies and constructs DeletePlace.
func NewDeletePlace(infra di.Infra) *DeletePlace {
	transactor := infra.Transactor
	reader := infra.Reader
	memberships := repository.NewMembership(reader)
	places := repository2.NewPlace(reader)

	return &DeletePlace{
		transactor:  transactor,
		memberships: memberships,
		places:      places,
	}
}

// NewPutPlace initializes dependencies and constructs PutPlace.
func NewPutPlace(infra di.Infra) *PutPlace {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	memberships := repository.NewMembership(reader)
	places := repository2.NewPlace(reader)

	return &PutPlace{
		transactor:  transactor,
		households:  households,
		memberships: memberships,
		places:      places,
	}
}
