// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	repository2 "github.com/mickamy/LocateDo/internal/feature/household/repository"
	"github.com/mickamy/LocateDo/internal/feature/place/repository"
)

// NewDeletePlace initializes dependencies and constructs DeletePlace.
func NewDeletePlace(infra di.Infra) *DeletePlace {
	transactor := infra.Transactor
	reader := infra.Reader
	places := repository.NewPlace(reader)

	return &DeletePlace{
		transactor: transactor,
		places:     places,
	}
}

// NewPutPlace initializes dependencies and constructs PutPlace.
func NewPutPlace(infra di.Infra) *PutPlace {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository2.NewHousehold(reader)
	places := repository.NewPlace(reader)

	return &PutPlace{
		transactor: transactor,
		households: households,
		places:     places,
	}
}
