// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	mapper2 "github.com/mickamy/LocateDo/internal/feature/category/mapper"
	model2 "github.com/mickamy/LocateDo/internal/feature/category/model"
	"github.com/mickamy/LocateDo/internal/feature/household/mapper"
	"github.com/mickamy/LocateDo/internal/feature/household/model"
	model3 "github.com/mickamy/LocateDo/internal/feature/place/model"
	model5 "github.com/mickamy/LocateDo/internal/feature/sync/model"
	model4 "github.com/mickamy/LocateDo/internal/feature/todo/model"
	categoryv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/category/v1"
	householdv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/household/v1"
	placev1 "github.com/mickamy/LocateDo/internal/gen/locatedo/place/v1"
	syncv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/sync/v1"
	todov1 "github.com/mickamy/LocateDo/internal/gen/locatedo/todo/v1"
	"github.com/mickamy/LocateDo/internal/lib/converters"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// MembershipToHouseholdv1 maps model.Membership to *householdv1.Membership.
func MembershipToHouseholdv1(src model.Membership) *householdv1.Membership {
	return &householdv1.Membership{
		HouseholdId: converters.UUIDToString(src.HouseholdID),
		UserId:      converters.UUIDToString(src.UserID),
		Role:        mapper.RoleToHouseholdv1(src.Role),
		DisplayName: src.DisplayName,
		JoinedAt:    converters.TimeToTimestamp(src.JoinedAt),
		UpdatedAt:   converters.TimeToTimestamp(src.UpdatedAt),
		Version:     src.Version,
	}
}

// CategoryToCategoryv1 maps model.Category to *categoryv1.Category.
func CategoryToCategoryv1(src model2.Category) *categoryv1.Category {
	return &categoryv1.Category{
		Id:          converters.UUIDToString(src.ID),
		HouseholdId: converters.UUIDToString(src.HouseholdID),
		Builtin:     mapper2.KeyToBuiltinCategory(src.BuiltinKey),
		Name:        src.Name,
		Icon:        src.Icon,
		Color:       src.Color,
		SortOrder:   src.SortOrder,
		UpdatedAt:   converters.TimeToTimestamp(src.UpdatedAt),
		Version:     src.Version,
	}
}

// PlaceToPlacev1 maps model.Place to *placev1.Place.
func PlaceToPlacev1(src model3.Place) *placev1.Place {
	var v0 *string
	if v1 := src.CategoryID; v1 != nil {
		v2 := converters.UUIDToString(*v1)
		v0 = &v2
	}
	return &placev1.Place{
		Id:          converters.UUIDToString(src.ID),
		HouseholdId: converters.UUIDToString(src.HouseholdID),
		Name:        src.Name,
		Lat:         src.Lat,
		Lng:         src.Lng,
		RadiusM:     src.RadiusM,
		CategoryId:  v0,
		SortOrder:   src.SortOrder,
		UpdatedAt:   converters.TimeToTimestamp(src.UpdatedAt),
		Version:     src.Version,
	}
}

// TodoToTodov1 maps model.Todo to *todov1.Todo.
func TodoToTodov1(src model4.Todo) *todov1.Todo {
	var v0 *string
	if v1 := src.AssigneeID; v1 != nil {
		v2 := converters.UUIDToString(*v1)
		v0 = &v2
	}
	var v3 *timestamppb.Timestamp
	if v4 := src.CompletedAt; v4 != nil {
		v3 = converters.TimeToTimestamp(*v4)
	}
	var v5 *string
	if v6 := src.CreatorID; v6 != nil {
		v7 := converters.UUIDToString(*v6)
		v5 = &v7
	}
	var v8 *string
	if v9 := src.CompleterID; v9 != nil {
		v10 := converters.UUIDToString(*v9)
		v8 = &v10
	}
	return &todov1.Todo{
		Id:          converters.UUIDToString(src.ID),
		HouseholdId: converters.UUIDToString(src.HouseholdID),
		PlaceId:     converters.UUIDToString(src.PlaceID),
		Title:       src.Title,
		AssigneeId:  v0,
		CompletedAt: v3,
		UpdatedAt:   converters.TimeToTimestamp(src.UpdatedAt),
		Version:     src.Version,
		CreatorId:   v5,
		CompleterId: v8,
	}
}

// DeletionToSyncv1 maps model.Deletion to *syncv1.Deletion.
func DeletionToSyncv1(src model5.Deletion) *syncv1.Deletion {
	return &syncv1.Deletion{
		Kind:    KindToEntityKind(src.Kind),
		Id:      converters.UUIDToString(src.ID),
		Version: src.Version,
	}
}
