// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/household/repository"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewAcceptInvite initializes dependencies and constructs AcceptInvite.
func NewAcceptInvite(infra di.Infra) *AcceptInvite {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	memberships := repository.NewMembership(reader)
	invites := repository.NewInvite(reader)

	return &AcceptInvite{
		transactor:  transactor,
		households:  households,
		memberships: memberships,
		invites:     invites,
	}
}

// NewCreateHousehold initializes dependencies and constructs CreateHousehold.
func NewCreateHousehold(infra di.Infra) *CreateHousehold {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	memberships := repository.NewMembership(reader)
	messages := outbox.NewRepository(reader)

	return &CreateHousehold{
		transactor:  transactor,
		households:  households,
		memberships: memberships,
		messages:    messages,
	}
}

// NewCreateInvite initializes dependencies and constructs CreateInvite.
func NewCreateInvite(infra di.Infra) *CreateInvite {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	memberships := repository.NewMembership(reader)
	invites := repository.NewInvite(reader)

	return &CreateInvite{
		transactor:  transactor,
		households:  households,
		memberships: memberships,
		invites:     invites,
	}
}

// NewForceResync initializes dependencies and constructs ForceResync.
func NewForceResync(infra di.Infra) *ForceResync {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	messages := outbox.NewRepository(reader)

	return &ForceResync{
		transactor: transactor,
		households: households,
		messages:   messages,
	}
}

// NewRemoveMember initializes dependencies and constructs RemoveMember.
func NewRemoveMember(infra di.Infra) *RemoveMember {
	transactor := infra.Transactor
	reader := infra.Reader
	memberships := repository.NewMembership(reader)

	return &RemoveMember{
		transactor:  transactor,
		memberships: memberships,
	}
}

// NewSetPlan initializes dependencies and constructs SetPlan.
func NewSetPlan(infra di.Infra) *SetPlan {
	transactor := infra.Transactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	messages := outbox.NewRepository(reader)

	return &SetPlan{
		transactor: transactor,
		households: households,
		messages:   messages,
	}
}
