// Code generated by kanna. DO NOT EDIT.

package server

import (
	"github.com/mickamy/LocateDo/internal/di"
)

// NewHandlers initializes dependencies and constructs Handlers.
func NewHandlers(infra di.Infra) *Handlers {
	return &Handlers{}
}
