// Code generated by kanna. DO NOT EDIT.

package server

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/handler"
	handler3 "github.com/mickamy/LocateDo/internal/feature/category/handler"
	handler6 "github.com/mickamy/LocateDo/internal/feature/device/handler"
	handler2 "github.com/mickamy/LocateDo/internal/feature/household/handler"
	handler4 "github.com/mickamy/LocateDo/internal/feature/place/handler"
	handler7 "github.com/mickamy/LocateDo/internal/feature/sync/handler"
	handler5 "github.com/mickamy/LocateDo/internal/feature/todo/handler"
	"github.com/mickamy/LocateDo/internal/server/health"
)

// NewHandlers initializes dependencies and constructs Handlers.
func NewHandlers(infra di.Infra, lib di.Lib) *Handlers {
	writer := infra.Writer
	reader := infra.Reader
	health2 := health.NewHealth(writer, reader)
	account := handler.NewAccount(infra, lib)
	household := handler2.NewHousehold(infra)
	category := handler3.NewCategory()
	place := handler4.NewPlace()
	todo := handler5.NewTodo()
	device := handler6.NewDevice()
	sync := handler7.NewSync()

	return &Handlers{
		Health:    health2,
		Account:   account,
		Household: household,
		Category:  category,
		Place:     place,
		Todo:      todo,
		Device:    device,
		Sync:      sync,
	}
}
