// Code generated by kanna. DO NOT EDIT.

package server

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/handler"
	handler3 "github.com/mickamy/LocateDo/internal/feature/category/handler"
	handler6 "github.com/mickamy/LocateDo/internal/feature/device/handler"
	handler2 "github.com/mickamy/LocateDo/internal/feature/household/handler"
	handler4 "github.com/mickamy/LocateDo/internal/feature/place/handler"
	handler7 "github.com/mickamy/LocateDo/internal/feature/sync/handler"
	handler5 "github.com/mickamy/LocateDo/internal/feature/todo/handler"
	"github.com/mickamy/LocateDo/internal/server/health"
	"github.com/mickamy/LocateDo/internal/server/interceptor"
)

// NewHandlers initializes dependencies and constructs Handlers.
func NewHandlers(config di.Config, infra di.Infra, lib di.Lib) *Handlers {
	interceptors := interceptor.NewInterceptors(config, infra, lib)
	writer := infra.Writer
	reader := infra.Reader
	health2 := health.NewHealth(writer, reader)
	account := handler.NewAccount(infra, lib)
	household := handler2.NewHousehold(infra)
	category := handler3.NewCategory(infra)
	place := handler4.NewPlace(infra)
	todo := handler5.NewTodo(infra)
	device := handler6.NewDevice()
	sync := handler7.NewSync(infra)

	return &Handlers{
		Interceptors: interceptors,
		Health:       health2,
		Account:      account,
		Household:    household,
		Category:     category,
		Place:        place,
		Todo:         todo,
		Device:       device,
		Sync:         sync,
	}
}
