app.bundle_name:
  infoplist: CFBundleName
permission.when_in_use:
  infoplist: NSLocationWhenInUseUsageDescription
permission.always:
  infoplist: NSLocationAlwaysAndWhenInUseUsageDescription
home.my_location:
  platforms: [android]
always_prompt.android_choose:
  platforms: [android]
settings.location.android_needs_always:
  platforms: [android]
permission.android_background:
  platforms: [android]
category.move_up:
  platforms: [android]
category.move_down:
  platforms: [android]
notification.channel_arrivals:
  platforms: [android]
settings.account.android_signed_in:
  platforms: [android]
settings.account.android_description:
  platforms: [android]
settings.account.android_sign_in:
  platforms: [android]
settings.account.benefits.android_privacy_message:
  platforms: [android]
settings.account.android_sign_out_confirm_message:
  platforms: [android]
settings.account.android_sign_out_unsynced_message:
  platforms: [android]
settings.account.android_replace_confirm_title:
  platforms: [android]
settings.account.android_replace_confirm_message:
  platforms: [android]
