// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"uuid"
)

type Todo struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	NotifyOn    string
	AssigneeID  *uuid.UUID
	CreatorID   *uuid.UUID
	CompletedAt *time.Time
	UpdatedAt   time.Time
	Version     int64
}
