// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const claimCompletionNotice = `-- name: ClaimCompletionNotice :many
UPDATE todo_completions c
SET notified_at = $1
FROM todos t
WHERE t.id = c.todo_id
  AND t.household_id = $2
  AND t.creator_id = $3
  AND t.completed_at IS NOT NULL
  AND c.completer_id = $4
  AND c.reopened_at IS NULL
  AND c.notified_at IS NULL
  AND NOT EXISTS (SELECT 1
                  FROM todo_completions p
                  WHERE p.todo_id = c.todo_id
                    AND p.notified_at IS NOT NULL)
RETURNING t.title, c.completed_at
`

type ClaimCompletionNoticeParams struct {
	NotifiedAt  *time.Time
	HouseholdID uuid.UUID
	CreatorID   *uuid.UUID
	CompleterID *uuid.UUID
}

type ClaimCompletionNoticeRow struct {
	Title       string
	CompletedAt time.Time
}

// Marks the creator's to-dos the completer checked off and nobody announced
// yet, skipping reopened ones and to-dos announced before, and returns them.
func (q *Queries) ClaimCompletionNotice(ctx context.Context, arg ClaimCompletionNoticeParams) ([]ClaimCompletionNoticeRow, error) {
	rows, err := q.db.Query(ctx, claimCompletionNotice,
		arg.NotifiedAt,
		arg.HouseholdID,
		arg.CreatorID,
		arg.CompleterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimCompletionNoticeRow
	for rows.Next() {
		var i ClaimCompletionNoticeRow
		if err := rows.Scan(&i.Title, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenTodos = `-- name: CountOpenTodos :one
SELECT count(*)
FROM todos
WHERE household_id = $1
  AND completed_at IS NULL
`

func (q *Queries) CountOpenTodos(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTodos, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE
FROM todos
WHERE id = $1
  AND household_id = $2
`

type DeleteTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo, arg.ID, arg.HouseholdID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, household_id, place_id, title, assignee_id, creator_id, completed_at, updated_at, version
FROM todos
WHERE id = $1
  AND household_id = $2
`

type GetTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, arg.ID, arg.HouseholdID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PlaceID,
		&i.Title,
		&i.AssigneeID,
		&i.CreatorID,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertCompletion = `-- name: InsertCompletion :exec
INSERT INTO todo_completions (todo_id, completer_id, completed_at)
VALUES ($1, $2, $3)
`

type InsertCompletionParams struct {
	TodoID      uuid.UUID
	CompleterID *uuid.UUID
	CompletedAt time.Time
}

func (q *Queries) InsertCompletion(ctx context.Context, arg InsertCompletionParams) error {
	_, err := q.db.Exec(ctx, insertCompletion, arg.TodoID, arg.CompleterID, arg.CompletedAt)
	return err
}

const reopenCompletions = `-- name: ReopenCompletions :exec
UPDATE todo_completions
SET reopened_at = $2
WHERE todo_id = $1
  AND reopened_at IS NULL
`

type ReopenCompletionsParams struct {
	TodoID     uuid.UUID
	ReopenedAt *time.Time
}

func (q *Queries) ReopenCompletions(ctx context.Context, arg ReopenCompletionsParams) error {
	_, err := q.db.Exec(ctx, reopenCompletions, arg.TodoID, arg.ReopenedAt)
	return err
}

const setTodoCompletion = `-- name: SetTodoCompletion :exec
UPDATE todos
SET completed_at = $3
WHERE id = $1
  AND household_id = $2
`

type SetTodoCompletionParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	CompletedAt *time.Time
}

func (q *Queries) SetTodoCompletion(ctx context.Context, arg SetTodoCompletionParams) error {
	_, err := q.db.Exec(ctx, setTodoCompletion, arg.ID, arg.HouseholdID, arg.CompletedAt)
	return err
}

const upsertTodo = `-- name: UpsertTodo :execrows
INSERT INTO todos (id, household_id, place_id, title, assignee_id, creator_id)
SELECT $1::uuid,
       $2::uuid,
       $3::uuid,
       $4::text,
       (SELECT m.user_id
        FROM memberships m
        WHERE m.user_id = $5::uuid
          AND m.household_id = $2::uuid),
       $6::uuid
WHERE EXISTS (SELECT 1
              FROM places p
              WHERE p.id = $3::uuid
                AND p.household_id = $2::uuid)
ON CONFLICT (id, household_id) DO UPDATE
    SET place_id    = EXCLUDED.place_id,
        title       = EXCLUDED.title,
        assignee_id = EXCLUDED.assignee_id
`

type UpsertTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	AssigneeID  *uuid.UUID
	CreatorID   *uuid.UUID
}

// Writes nothing when the place is not in the household. An assignee who is
// not a member resolves to NULL. completed_at and creator_id are left alone on
// update.
func (q *Queries) UpsertTodo(ctx context.Context, arg UpsertTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertTodo,
		arg.ID,
		arg.HouseholdID,
		arg.PlaceID,
		arg.Title,
		arg.AssigneeID,
		arg.CreatorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
