// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const countOpenTodos = `-- name: CountOpenTodos :one
SELECT count(*)
FROM todos
WHERE household_id = $1
  AND completed_at IS NULL
`

func (q *Queries) CountOpenTodos(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTodos, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE
FROM todos
WHERE id = $1
  AND household_id = $2
`

type DeleteTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo, arg.ID, arg.HouseholdID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, household_id, place_id, title, assignee_id, completed_at, updated_at, version
FROM todos
WHERE id = $1
  AND household_id = $2
`

type GetTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, arg.ID, arg.HouseholdID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PlaceID,
		&i.Title,
		&i.AssigneeID,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const setTodoCompletion = `-- name: SetTodoCompletion :exec
UPDATE todos
SET completed_at = $3
WHERE id = $1
  AND household_id = $2
`

type SetTodoCompletionParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	CompletedAt *time.Time
}

func (q *Queries) SetTodoCompletion(ctx context.Context, arg SetTodoCompletionParams) error {
	_, err := q.db.Exec(ctx, setTodoCompletion, arg.ID, arg.HouseholdID, arg.CompletedAt)
	return err
}

const upsertTodo = `-- name: UpsertTodo :execrows
INSERT INTO todos (id, household_id, place_id, title, assignee_id)
SELECT $1::uuid,
       $2::uuid,
       $3::uuid,
       $4::text,
       (SELECT m.user_id
        FROM memberships m
        WHERE m.user_id = $5::uuid
          AND m.household_id = $2::uuid)
WHERE EXISTS (SELECT 1
              FROM places p
              WHERE p.id = $3::uuid
                AND p.household_id = $2::uuid)
ON CONFLICT (id, household_id) DO UPDATE
    SET place_id    = EXCLUDED.place_id,
        title       = EXCLUDED.title,
        assignee_id = EXCLUDED.assignee_id
`

type UpsertTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	AssigneeID  *uuid.UUID
}

// Writes nothing when the place is not in the household. An assignee who is
// not a member resolves to NULL. completed_at is left alone on update.
func (q *Queries) UpsertTodo(ctx context.Context, arg UpsertTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertTodo,
		arg.ID,
		arg.HouseholdID,
		arg.PlaceID,
		arg.Title,
		arg.AssigneeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
