// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/sync/usecase"
)

// NewSync initializes dependencies and constructs Sync.
func NewSync(infra di.Infra) *Sync {
	pull := usecase.NewPull(infra)

	return &Sync{
		pull: pull,
	}
}
