// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/household/usecase"
)

// NewHousehold initializes dependencies and constructs Household.
func NewHousehold(infra di.Infra) *Household {
	createHousehold := usecase.NewCreateHousehold(infra)
	createInvite := usecase.NewCreateInvite(infra)
	acceptInvite := usecase.NewAcceptInvite(infra)
	removeMember := usecase.NewRemoveMember(infra)

	return &Household{
		createHousehold: createHousehold,
		createInvite:    createInvite,
		acceptInvite:    acceptInvite,
		removeMember:    removeMember,
	}
}
