// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"
	"uuid"

	"github.com/mickamy/LocateDo/internal/feature/place/model"
	placev1 "github.com/mickamy/LocateDo/internal/gen/locatedo/place/v1"
)

// PlaceFromPlaceInput maps *placev1.PlaceInput to model.Place.
func PlaceFromPlaceInput(src *placev1.PlaceInput) (model.Place, error) {
	if src == nil {
		return model.Place{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.Place{}, fmt.Errorf("map model.Place.ID: %w", err0)
	}
	var v2 *uuid.UUID
	if v3 := src.CategoryId; v3 != nil {
		var v4 uuid.UUID
		v6, err5 := uuid.Parse(*v3)
		if err5 != nil {
			return model.Place{}, fmt.Errorf("map model.Place.CategoryID: %w", err5)
		}
		v4 = v6
		v2 = &v4
	}
	return model.Place{
		ID:         v1,
		Name:       src.GetName(),
		Lat:        src.GetLat(),
		Lng:        src.GetLng(),
		RadiusM:    src.GetRadiusM(),
		CategoryID: v2,
		SortOrder:  src.GetSortOrder(),
	}, nil
}
