// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const claimMessage = `-- name: ClaimMessage :one
UPDATE outbox_messages
SET status      = 'running',
    lease_until = $1
WHERE id = (SELECT due.id
            FROM outbox_messages due
            WHERE (due.status = 'pending' AND due.run_at <= $2)
               OR (due.status = 'running' AND due.lease_until <= $2)
            ORDER BY due.run_at
            LIMIT 1 FOR UPDATE SKIP LOCKED)
RETURNING id, kind, payload, dedupe_key, run_at, attempts, created_at
`

type ClaimMessageParams struct {
	LeaseUntil *time.Time
	Now        time.Time
}

type ClaimMessageRow struct {
	ID        uuid.UUID
	Kind      string
	Payload   []byte
	DedupeKey *string
	RunAt     time.Time
	Attempts  int32
	CreatedAt time.Time
}

// Takes the oldest due message, or one whose lease ran out because its
// worker died, and leases it until lease_until.
func (q *Queries) ClaimMessage(ctx context.Context, arg ClaimMessageParams) (ClaimMessageRow, error) {
	row := q.db.QueryRow(ctx, claimMessage, arg.LeaseUntil, arg.Now)
	var i ClaimMessageRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.RunAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const completeMessage = `-- name: CompleteMessage :exec
DELETE
FROM outbox_messages
WHERE id = $1
`

func (q *Queries) CompleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeMessage, id)
	return err
}

const enqueueMessage = `-- name: EnqueueMessage :exec
INSERT INTO outbox_messages (kind, payload, dedupe_key, run_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (dedupe_key) WHERE status = 'pending' DO NOTHING
`

type EnqueueMessageParams struct {
	Kind      string
	Payload   []byte
	DedupeKey *string
	RunAt     time.Time
}

// A pending message with the same dedupe key makes this a no-op.
func (q *Queries) EnqueueMessage(ctx context.Context, arg EnqueueMessageParams) error {
	_, err := q.db.Exec(ctx, enqueueMessage,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.RunAt,
	)
	return err
}

const getOutboxHealth = `-- name: GetOutboxHealth :one
SELECT coalesce(extract(EPOCH FROM $1::timestamptz - min(CASE
    WHEN status = 'pending' AND run_at <= $1 THEN run_at
    WHEN status = 'running' AND lease_until <= $1 THEN lease_until
    END)), 0)::bigint                                                            AS overdue_seconds,
       coalesce(extract(EPOCH FROM $1::timestamptz - min(created_at)
                                    FILTER (WHERE status IN ('pending', 'running'))), 0)::bigint AS oldest_seconds,
       count(*) FILTER (WHERE status = 'dead' AND dead_at > $2::timestamptz)::bigint       AS dead
FROM outbox_messages
`

type GetOutboxHealthParams struct {
	Now       time.Time
	DeadSince time.Time
}

type GetOutboxHealthRow struct {
	OverdueSeconds int64
	OldestSeconds  int64
	Dead           int64
}

// Overdue: due pending messages and running ones whose lease ran out, measured
// from when they should have been taken. Oldest: anything not yet delivered.
func (q *Queries) GetOutboxHealth(ctx context.Context, arg GetOutboxHealthParams) (GetOutboxHealthRow, error) {
	row := q.db.QueryRow(ctx, getOutboxHealth, arg.Now, arg.DeadSince)
	var i GetOutboxHealthRow
	err := row.Scan(&i.OverdueSeconds, &i.OldestSeconds, &i.Dead)
	return i, err
}

const killMessage = `-- name: KillMessage :exec
UPDATE outbox_messages
SET attempts    = attempts + 1,
    status      = 'dead',
    lease_until = NULL,
    dead_at     = $1::timestamptz,
    last_error  = $2
WHERE id = $3
`

type KillMessageParams struct {
	DeadAt    time.Time
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) KillMessage(ctx context.Context, arg KillMessageParams) error {
	_, err := q.db.Exec(ctx, killMessage, arg.DeadAt, arg.LastError, arg.ID)
	return err
}

const retryMessage = `-- name: RetryMessage :execrows
UPDATE outbox_messages m
SET status      = 'pending',
    lease_until = NULL,
    attempts    = m.attempts + 1,
    run_at      = $2,
    last_error  = $3
WHERE m.id = $1
  AND NOT EXISTS (SELECT 1
                  FROM outbox_messages p
                  WHERE p.status = 'pending'
                    AND p.dedupe_key = m.dedupe_key)
`

type RetryMessageParams struct {
	ID        uuid.UUID
	RunAt     time.Time
	LastError *string
}

// Skipped when a pending message with the same dedupe key already waits.
func (q *Queries) RetryMessage(ctx context.Context, arg RetryMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryMessage, arg.ID, arg.RunAt, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepDeadMessages = `-- name: SweepDeadMessages :execrows
DELETE
FROM outbox_messages
WHERE status = 'dead'
  AND dead_at < $1::timestamptz
`

func (q *Queries) SweepDeadMessages(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepDeadMessages, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
