// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/household/repository"
	repository2 "github.com/mickamy/LocateDo/internal/feature/sync/repository"
)

// NewPull initializes dependencies and constructs Pull.
func NewPull(infra di.Infra) *Pull {
	readTransactor := infra.ReadTransactor
	reader := infra.Reader
	households := repository.NewHousehold(reader)
	changes := repository2.NewChanges(reader)

	return &Pull{
		readTransactor: readTransactor,
		households:     households,
		changes:        changes,
	}
}
