// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	repository2 "github.com/mickamy/LocateDo/internal/feature/category/repository"
	"github.com/mickamy/LocateDo/internal/feature/household/repository"
)

// NewDeleteCategory initializes dependencies and constructs DeleteCategory.
func NewDeleteCategory(infra di.Infra) *DeleteCategory {
	transactor := infra.Transactor
	reader := infra.Reader
	memberships := repository.NewMembership(reader)
	categories := repository2.NewCategory(reader)

	return &DeleteCategory{
		transactor:  transactor,
		memberships: memberships,
		categories:  categories,
	}
}

// NewPutCategory initializes dependencies and constructs PutCategory.
func NewPutCategory(infra di.Infra) *PutCategory {
	transactor := infra.Transactor
	reader := infra.Reader
	memberships := repository.NewMembership(reader)
	categories := repository2.NewCategory(reader)

	return &PutCategory{
		transactor:  transactor,
		memberships: memberships,
		categories:  categories,
	}
}
