// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/category/repository"
)

// NewDeleteCategory initializes dependencies and constructs DeleteCategory.
func NewDeleteCategory(infra di.Infra) *DeleteCategory {
	transactor := infra.Transactor
	reader := infra.Reader
	categories := repository.NewCategory(reader)

	return &DeleteCategory{
		transactor: transactor,
		categories: categories,
	}
}

// NewPutCategory initializes dependencies and constructs PutCategory.
func NewPutCategory(infra di.Infra) *PutCategory {
	transactor := infra.Transactor
	reader := infra.Reader
	categories := repository.NewCategory(reader)

	return &PutCategory{
		transactor: transactor,
		categories: categories,
	}
}
