-- One row per Analytics event with the parameters LocateDo sends as columns.
SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  TIMESTAMP_MICROS(event_timestamp) AS event_time,
  event_name,
  user_pseudo_id,
  app_info.version AS app_version,
  geo.country AS country,
  device.language AS language,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'firebase_screen') AS screen,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'mode') AS mode,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'step') AS step,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'source') AS source,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'category') AS category,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'via') AS via,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'kind') AS kind,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'trigger') AS paywall_trigger,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'plan') AS plan,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'from') AS auth_from,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'to') AS auth_to,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'location_auth') AS location_auth,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'notification_auth') AS notification_auth,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'reason') AS reason,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'result') AS result,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'household_plan') AS household_plan,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'place_count') AS place_count,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'open_todo_count') AS open_todo_count,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'completed_todo_count_7d') AS completed_todo_count_7d,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'places_with_open_todos') AS places_with_open_todos,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'custom_category_count') AS custom_category_count,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'household_members') AS household_members,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'days_since_install') AS days_since_install,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'open_todos') AS open_todos,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'place_open_todos') AS place_open_todos,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'age_days') AS age_days,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'age_hours') AS age_hours,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'radius_m') AS radius_m,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'duration_s') AS duration_s,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'latency_s') AS latency_s,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'assigned') AS assigned,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'signed_in') AS signed_in,
  (SELECT value.int_value FROM UNNEST(event_params) WHERE key = 'precise_location') AS precise_location,
  -- Sent by RevenueCat's Firebase integration on its rc_* events.
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'product_id') AS product_id,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'currency') AS currency,
  (
    SELECT COALESCE(value.double_value, value.float_value, CAST(value.int_value AS FLOAT64))
    FROM UNNEST(event_params) WHERE key = 'value'
  ) AS value,
  event_value_in_usd
FROM `__PROJECT__.__SOURCE__.events_*`
