// Code generated by kanna. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mickamy/LocateDo/config"
)

// NewConfig initializes dependencies and constructs Config.
func NewConfig() Config {
	app := config.ParseApp()
	database := config.ParseDatabase()

	return Config{
		App:      app,
		Database: database,
	}
}

// NewInfra initializes dependencies and constructs Infra.
func NewInfra(context2 context.Context, config2 Config) (Infra, error) {
	database := config2.Database
	writer, err := provideWriter(context2, database)
	if err != nil {
		return *new(Infra), err
	}
	reader, err := provideReader(context2, database, writer)
	if err != nil {
		return *new(Infra), err
	}
	transactor := provideTransactor(writer)
	readTransactor := provideReadTransactor(reader)

	return Infra{
		Writer:         writer,
		Reader:         reader,
		Transactor:     transactor,
		ReadTransactor: readTransactor,
	}, nil
}

// MustNewInfra initializes dependencies and constructs Infra or panics on failure.
func MustNewInfra(context2 context.Context, config2 Config) Infra {
	v, err := NewInfra(context2, config2)
	if err != nil {
		panic(err)
	}
	return v
}
