// Code generated by kanna. DO NOT EDIT.

package di

import (
	"context"
	"github.com/mickamy/LocateDo/config"
)

// NewConfig initializes dependencies and constructs Config.
func NewConfig() Config {
	app := config.ParseApp()
	database := config.ParseDatabase()
	auth := config.ParseAuth()
	apple := config.ParseApple()
	google := config.ParseGoogle()
	apNs := config.ParseAPNs()
	fcm := config.ParseFCM()
	revenueCat := config.ParseRevenueCat()

	return Config{
		App:        app,
		Database:   database,
		Auth:       auth,
		Apple:      apple,
		Google:     google,
		APNs:       apNs,
		FCM:        fcm,
		RevenueCat: revenueCat,
	}
}

// NewInfra initializes dependencies and constructs Infra.
func NewInfra(context2 context.Context, config2 Config) (Infra, error) {
	database := config2.Database
	writer, err := provideWriter(context2, database)
	if err != nil {
		return *new(Infra), err
	}
	reader, err := provideReader(context2, database, writer)
	if err != nil {
		return *new(Infra), err
	}
	transactor := provideTransactor(writer)
	readTransactor := provideReadTransactor(reader)
	apple := config2.Apple
	apple2, err := provideApple(apple)
	if err != nil {
		return *new(Infra), err
	}
	google := config2.Google
	google2 := provideGoogle(google)
	apNs := config2.APNs
	apNs2, err := provideAPNs(apNs, apple)
	if err != nil {
		return *new(Infra), err
	}
	fcm := config2.FCM
	fcm2, err := provideFCM(fcm)
	if err != nil {
		return *new(Infra), err
	}
	revenueCat := config2.RevenueCat
	entitlements := provideRevenueCat(revenueCat)

	return Infra{
		Writer:         writer,
		Reader:         reader,
		Transactor:     transactor,
		ReadTransactor: readTransactor,
		Apple:          apple2,
		Google:         google2,
		APNs:           apNs2,
		FCM:            fcm2,
		Entitlements:   entitlements,
	}, nil
}

// MustNewInfra initializes dependencies and constructs Infra or panics on failure.
func MustNewInfra(context2 context.Context, config2 Config) Infra {
	v, err := NewInfra(context2, config2)
	if err != nil {
		panic(err)
	}
	return v
}

// NewLib initializes dependencies and constructs Lib.
func NewLib(config2 Config) (Lib, error) {
	auth := config2.Auth
	signer, err := provideSigner(auth)
	if err != nil {
		return *new(Lib), err
	}
	box, err := provideBox(auth)
	if err != nil {
		return *new(Lib), err
	}

	return Lib{
		Signer: signer,
		Box:    box,
	}, nil
}

// MustNewLib initializes dependencies and constructs Lib or panics on failure.
func MustNewLib(config2 Config) Lib {
	v, err := NewLib(config2)
	if err != nil {
		panic(err)
	}
	return v
}
