// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/device/usecase"
)

// NewDevice initializes dependencies and constructs Device.
func NewDevice(infra di.Infra) *Device {
	registerDevice := usecase.NewRegisterDevice(infra)

	return &Device{
		registerDevice: registerDevice,
	}
}
