// Code generated by kanna. DO NOT EDIT.

package handler

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/todo/usecase"
)

// NewTodo initializes dependencies and constructs Todo.
func NewTodo(infra di.Infra) *Todo {
	putTodo := usecase.NewPutTodo(infra)
	setTodoCompletion := usecase.NewSetTodoCompletion(infra)
	deleteTodo := usecase.NewDeleteTodo(infra)

	return &Todo{
		putTodo:           putTodo,
		setTodoCompletion: setTodoCompletion,
		deleteTodo:        deleteTodo,
	}
}
