// Code generated by kanna. DO NOT EDIT.

package fixture

import (
	"uuid"

	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/LocateDo/internal/feature/device/model"
)

func Device(setters ...func(m *model.Device)) model.Device {
	m := model.Device{
		ID:                uuid.MustParse(gofakeit.UUID()),
		Platform:          model.Platform(mustGenerate("{randomstring:[ios,android]}")),
		PushToken:         gofakeit.UUID(),
		APNsEnvironment:   model.APNsEnvironment(mustGenerate("{randomstring:[sandbox,production]}")),
		Language:          model.Language(mustGenerate("{randomstring:[en,ja]}")),
		PromotionsConsent: gofakeit.Bool(),
		LastSeenAt:        gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func mustGenerate(template string) string {
	s, err := gofakeit.Generate(template)
	if err != nil {
		panic(err)
	}
	return s
}
