// Code generated by kanna. DO NOT EDIT.

package job

import (
	"github.com/mickamy/LocateDo/internal/di"
)

// NewRevokeAppleToken initializes dependencies and constructs RevokeAppleToken.
func NewRevokeAppleToken(infra di.Infra, lib di.Lib) *RevokeAppleToken {
	apple := infra.Apple
	box := lib.Box

	return &RevokeAppleToken{
		apple: apple,
		box:   box,
	}
}
