// Code generated by kanna. DO NOT EDIT.

package job

import (
	"github.com/mickamy/LocateDo/internal/di"
	repository3 "github.com/mickamy/LocateDo/internal/feature/account/repository"
	"github.com/mickamy/LocateDo/internal/feature/device/repository"
	repository2 "github.com/mickamy/LocateDo/internal/feature/household/repository"
	"github.com/mickamy/LocateDo/internal/feature/household/usecase"
	repository4 "github.com/mickamy/LocateDo/internal/feature/sync/repository"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewPushHousehold initializes dependencies and constructs PushHousehold.
func NewPushHousehold(infra di.Infra) *PushHousehold {
	transactor := infra.Transactor
	reader := infra.Reader
	devices := repository.NewDevice(reader)
	apns := infra.APNs
	fcm := infra.FCM

	return &PushHousehold{
		transactor: transactor,
		devices:    devices,
		apns:       apns,
		fcm:        fcm,
	}
}

// NewReconcileEntitlements initializes dependencies and constructs ReconcileEntitlements.
func NewReconcileEntitlements(infra di.Infra) *ReconcileEntitlements {
	transactor := infra.Transactor
	reader := infra.Reader
	plans := repository2.NewPlan(reader)
	messages := outbox.NewRepository(reader)

	return &ReconcileEntitlements{
		transactor: transactor,
		plans:      plans,
		messages:   messages,
	}
}

// NewReportOutbox initializes dependencies and constructs ReportOutbox.
func NewReportOutbox(infra di.Infra) *ReportOutbox {
	reader := infra.Reader
	messages := outbox.NewRepository(reader)

	return &ReportOutbox{
		messages: messages,
	}
}

// NewRevokeAppleToken initializes dependencies and constructs RevokeAppleToken.
func NewRevokeAppleToken(infra di.Infra, lib di.Lib) *RevokeAppleToken {
	apple := infra.Apple
	box := lib.Box

	return &RevokeAppleToken{
		apple: apple,
		box:   box,
	}
}

// NewSweepDeadMessages initializes dependencies and constructs SweepDeadMessages.
func NewSweepDeadMessages(infra di.Infra) *SweepDeadMessages {
	transactor := infra.Transactor
	reader := infra.Reader
	messages := outbox.NewRepository(reader)

	return &SweepDeadMessages{
		transactor: transactor,
		messages:   messages,
	}
}

// NewSweepRefreshTokens initializes dependencies and constructs SweepRefreshTokens.
func NewSweepRefreshTokens(infra di.Infra) *SweepRefreshTokens {
	transactor := infra.Transactor
	reader := infra.Reader
	refreshTokens := repository3.NewRefreshToken(reader)

	return &SweepRefreshTokens{
		transactor:    transactor,
		refreshTokens: refreshTokens,
	}
}

// NewSweepTombstones initializes dependencies and constructs SweepTombstones.
func NewSweepTombstones(infra di.Infra) *SweepTombstones {
	transactor := infra.Transactor
	reader := infra.Reader
	tombstones := repository4.NewTombstones(reader)

	return &SweepTombstones{
		transactor: transactor,
		tombstones: tombstones,
	}
}

// NewSyncEntitlement initializes dependencies and constructs SyncEntitlement.
func NewSyncEntitlement(infra di.Infra) *SyncEntitlement {
	setPlan := usecase.NewSetPlan(infra)
	entitlements := infra.Entitlements

	return &SyncEntitlement{
		setPlan:      setPlan,
		entitlements: entitlements,
	}
}
