// Code generated by kanna. DO NOT EDIT.

package fixture

import (
	"uuid"

	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/LocateDo/internal/feature/todo/model"
)

func Todo(setters ...func(m *model.Todo)) model.Todo {
	m := model.Todo{
		ID:          uuid.MustParse(gofakeit.UUID()),
		HouseholdID: uuid.MustParse(gofakeit.UUID()),
		PlaceID:     uuid.MustParse(gofakeit.UUID()),
		Title:       gofakeit.Word(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}
