// Code generated by kanna. DO NOT EDIT.

package fixture

import (
	"uuid"

	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/LocateDo/internal/feature/todo/model"
)

func CompletedTodo(setters ...func(m *model.CompletedTodo)) model.CompletedTodo {
	m := model.CompletedTodo{
		Title:       gofakeit.Word(),
		CompletedAt: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func Todo(setters ...func(m *model.Todo)) model.Todo {
	m := model.Todo{
		ID:          uuid.MustParse(gofakeit.UUID()),
		HouseholdID: uuid.MustParse(gofakeit.UUID()),
		PlaceID:     uuid.MustParse(gofakeit.UUID()),
		Title:       gofakeit.Word(),
		Trigger:     Trigger(),
		UpdatedAt:   gofakeit.Date(),
		Version:     gofakeit.Int64(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func Trigger(setters ...func(m *model.Trigger)) model.Trigger {
	m := model.Trigger{
		Event: model.PlaceEvent(mustGenerate("{randomstring:[arrival,departure]}")),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func mustGenerate(template string) string {
	s, err := gofakeit.Generate(template)
	if err != nil {
		panic(err)
	}
	return s
}
