// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE household_invites
SET accepted_by = $1,
    accepted_at = $2
WHERE token_hash = $3
  AND accepted_at IS NULL
RETURNING id, household_id, created_by, expires_at
`

type AcceptInviteParams struct {
	AcceptedBy *uuid.UUID
	AcceptedAt *time.Time
	TokenHash  []byte
}

type AcceptInviteRow struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	CreatedBy   uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) (AcceptInviteRow, error) {
	row := q.db.QueryRow(ctx, acceptInvite, arg.AcceptedBy, arg.AcceptedAt, arg.TokenHash)
	var i AcceptInviteRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const countMemberships = `-- name: CountMemberships :one
SELECT count(*)
FROM memberships
WHERE household_id = $1
`

func (q *Queries) CountMemberships(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberships, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (id, owner_id)
VALUES ($1, $2)
RETURNING id, owner_id, plan, created_at
`

type CreateHouseholdParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type CreateHouseholdRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Plan      string
	CreatedAt time.Time
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (CreateHouseholdRow, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.ID, arg.OwnerID)
	var i CreateHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO household_invites (household_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateInviteParams struct {
	HouseholdID uuid.UUID
	TokenHash   []byte
	CreatedBy   uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.HouseholdID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (household_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.HouseholdID, arg.UserID, arg.Role)
	return err
}

const deferConstraints = `-- name: DeferConstraints :exec
SET CONSTRAINTS ALL DEFERRED
`

func (q *Queries) DeferConstraints(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deferConstraints)
	return err
}

const deleteHousehold = `-- name: DeleteHousehold :execrows
DELETE
FROM households
WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHousehold, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE
FROM memberships
WHERE household_id = $1
  AND user_id = $2
`

type DeleteMembershipParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, owner_id, plan, created_at
FROM households
WHERE id = $1
`

type GetHouseholdRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Plan      string
	CreatedAt time.Time
}

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (GetHouseholdRow, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i GetHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByUser = `-- name: GetMembershipByUser :one
SELECT household_id, user_id, role, joined_at
FROM memberships
WHERE user_id = $1
`

type GetMembershipByUserRow struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
	JoinedAt    time.Time
}

func (q *Queries) GetMembershipByUser(ctx context.Context, userID uuid.UUID) (GetMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUser, userID)
	var i GetMembershipByUserRow
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const moveCustomCategories = `-- name: MoveCustomCategories :exec
UPDATE categories
SET household_id = $1
WHERE household_id = $2
  AND builtin_key IS NULL
`

type MoveCustomCategoriesParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MoveCustomCategories(ctx context.Context, arg MoveCustomCategoriesParams) error {
	_, err := q.db.Exec(ctx, moveCustomCategories, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const movePlaces = `-- name: MovePlaces :exec
UPDATE places
SET household_id = $1
WHERE household_id = $2
`

type MovePlacesParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MovePlaces(ctx context.Context, arg MovePlacesParams) error {
	_, err := q.db.Exec(ctx, movePlaces, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const moveTodos = `-- name: MoveTodos :exec
UPDATE todos
SET household_id = $1
WHERE household_id = $2
`

type MoveTodosParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MoveTodos(ctx context.Context, arg MoveTodosParams) error {
	_, err := q.db.Exec(ctx, moveTodos, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const remapBuiltinCategories = `-- name: RemapBuiltinCategories :exec
UPDATE places p
SET category_id = t.id
FROM categories o
         LEFT JOIN categories t
                   ON t.household_id = $2
                       AND t.builtin_key = o.builtin_key
WHERE p.household_id = $1
  AND p.category_id = o.id
  AND o.builtin_key IS NOT NULL
`

type RemapBuiltinCategoriesParams struct {
	FromHouseholdID uuid.UUID
	ToHouseholdID   uuid.UUID
}

func (q *Queries) RemapBuiltinCategories(ctx context.Context, arg RemapBuiltinCategoriesParams) error {
	_, err := q.db.Exec(ctx, remapBuiltinCategories, arg.FromHouseholdID, arg.ToHouseholdID)
	return err
}
