// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE household_invites
SET accepted_by = $1,
    accepted_at = $2
WHERE token_hash = $3
  AND accepted_at IS NULL
RETURNING id, household_id, created_by, expires_at
`

type AcceptInviteParams struct {
	AcceptedBy *uuid.UUID
	AcceptedAt *time.Time
	TokenHash  []byte
}

type AcceptInviteRow struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	CreatedBy   uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) (AcceptInviteRow, error) {
	row := q.db.QueryRow(ctx, acceptInvite, arg.AcceptedBy, arg.AcceptedAt, arg.TokenHash)
	var i AcceptInviteRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const advanceAllHouseholdVersions = `-- name: AdvanceAllHouseholdVersions :many
UPDATE households
SET version       = version + $1,
    swept_version = version + $1
RETURNING id
`

// Both columns take the pre-update version, so every cursor a device holds
// falls below swept_version and its next Pull resets.
func (q *Queries) AdvanceAllHouseholdVersions(ctx context.Context, step int64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, advanceAllHouseholdVersions, step)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMemberships = `-- name: CountMemberships :one
SELECT count(*)
FROM memberships
WHERE household_id = $1
`

func (q *Queries) CountMemberships(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberships, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (id, owner_id)
VALUES ($1, $2)
RETURNING id, owner_id, plan, version, swept_version, created_at
`

type CreateHouseholdParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.ID, arg.OwnerID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.Version,
		&i.SweptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO household_invites (household_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateInviteParams struct {
	HouseholdID uuid.UUID
	TokenHash   []byte
	CreatedBy   uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.HouseholdID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (household_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.HouseholdID, arg.UserID, arg.Role)
	return err
}

const deferConstraints = `-- name: DeferConstraints :exec
SET CONSTRAINTS ALL DEFERRED
`

func (q *Queries) DeferConstraints(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deferConstraints)
	return err
}

const deleteHousehold = `-- name: DeleteHousehold :execrows
DELETE
FROM households
WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHousehold, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE
FROM memberships
WHERE household_id = $1
  AND user_id = $2
`

type DeleteMembershipParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, owner_id, plan, version, swept_version, created_at
FROM households
WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.Version,
		&i.SweptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdByOwner = `-- name: GetHouseholdByOwner :one
SELECT id, owner_id, plan, version, swept_version, created_at
FROM households
WHERE owner_id = $1
`

func (q *Queries) GetHouseholdByOwner(ctx context.Context, ownerID uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByOwner, ownerID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.Version,
		&i.SweptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdForUpdate = `-- name: GetHouseholdForUpdate :one
SELECT id, owner_id, plan, version, swept_version, created_at
FROM households
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetHouseholdForUpdate(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdForUpdate, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Plan,
		&i.Version,
		&i.SweptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByUser = `-- name: GetMembershipByUser :one
SELECT m.household_id, m.user_id, m.role, u.display_name, m.joined_at, m.updated_at, m.version
FROM memberships m
         JOIN users u ON u.id = m.user_id
WHERE m.user_id = $1
`

type GetMembershipByUserRow struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
	DisplayName string
	JoinedAt    time.Time
	UpdatedAt   time.Time
	Version     int64
}

func (q *Queries) GetMembershipByUser(ctx context.Context, userID uuid.UUID) (GetMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUser, userID)
	var i GetMembershipByUserRow
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const importCategory = `-- name: ImportCategory :exec
INSERT INTO categories (id, household_id, builtin_key, name, icon, color, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type ImportCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BuiltinKey  *string
	Name        *string
	Icon        string
	Color       string
	SortOrder   int32
}

func (q *Queries) ImportCategory(ctx context.Context, arg ImportCategoryParams) error {
	_, err := q.db.Exec(ctx, importCategory,
		arg.ID,
		arg.HouseholdID,
		arg.BuiltinKey,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.SortOrder,
	)
	return err
}

const importCompletion = `-- name: ImportCompletion :exec
INSERT INTO todo_completions (todo_id, completer_id, completed_at)
VALUES ($1, $2, $3)
`

type ImportCompletionParams struct {
	TodoID      uuid.UUID
	CompleterID *uuid.UUID
	CompletedAt time.Time
}

func (q *Queries) ImportCompletion(ctx context.Context, arg ImportCompletionParams) error {
	_, err := q.db.Exec(ctx, importCompletion, arg.TodoID, arg.CompleterID, arg.CompletedAt)
	return err
}

const importPlace = `-- name: ImportPlace :exec
INSERT INTO places (id, household_id, name, lat, lng, radius_m, category_id, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type ImportPlaceParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	Lat         float64
	Lng         float64
	RadiusM     int32
	CategoryID  *uuid.UUID
	SortOrder   int32
}

func (q *Queries) ImportPlace(ctx context.Context, arg ImportPlaceParams) error {
	_, err := q.db.Exec(ctx, importPlace,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.RadiusM,
		arg.CategoryID,
		arg.SortOrder,
	)
	return err
}

const importTodo = `-- name: ImportTodo :exec
INSERT INTO todos (id, household_id, place_id, title, notify_on, assignee_id, creator_id, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type ImportTodoParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	NotifyOn    string
	AssigneeID  *uuid.UUID
	CreatorID   *uuid.UUID
	CompletedAt *time.Time
}

func (q *Queries) ImportTodo(ctx context.Context, arg ImportTodoParams) error {
	_, err := q.db.Exec(ctx, importTodo,
		arg.ID,
		arg.HouseholdID,
		arg.PlaceID,
		arg.Title,
		arg.NotifyOn,
		arg.AssigneeID,
		arg.CreatorID,
		arg.CompletedAt,
	)
	return err
}

const listHouseholdOwnersByPlan = `-- name: ListHouseholdOwnersByPlan :many
SELECT owner_id
FROM households
WHERE plan = $1
ORDER BY owner_id
`

func (q *Queries) ListHouseholdOwnersByPlan(ctx context.Context, plan string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listHouseholdOwnersByPlan, plan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var owner_id uuid.UUID
		if err := rows.Scan(&owner_id); err != nil {
			return nil, err
		}
		items = append(items, owner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCustomCategories = `-- name: MoveCustomCategories :exec
UPDATE categories
SET household_id = $1
WHERE household_id = $2
  AND builtin_key IS NULL
`

type MoveCustomCategoriesParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MoveCustomCategories(ctx context.Context, arg MoveCustomCategoriesParams) error {
	_, err := q.db.Exec(ctx, moveCustomCategories, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const movePlaces = `-- name: MovePlaces :exec
UPDATE places
SET household_id = $1
WHERE household_id = $2
`

type MovePlacesParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MovePlaces(ctx context.Context, arg MovePlacesParams) error {
	_, err := q.db.Exec(ctx, movePlaces, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const moveTodos = `-- name: MoveTodos :exec
UPDATE todos
SET household_id = $1
WHERE household_id = $2
`

type MoveTodosParams struct {
	ToHouseholdID   uuid.UUID
	FromHouseholdID uuid.UUID
}

func (q *Queries) MoveTodos(ctx context.Context, arg MoveTodosParams) error {
	_, err := q.db.Exec(ctx, moveTodos, arg.ToHouseholdID, arg.FromHouseholdID)
	return err
}

const releaseAssignments = `-- name: ReleaseAssignments :exec
UPDATE todos
SET assignee_id = NULL
WHERE household_id = $1
  AND assignee_id = $2::uuid
`

type ReleaseAssignmentsParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) ReleaseAssignments(ctx context.Context, arg ReleaseAssignmentsParams) error {
	_, err := q.db.Exec(ctx, releaseAssignments, arg.HouseholdID, arg.UserID)
	return err
}

const remapBuiltinCategories = `-- name: RemapBuiltinCategories :exec
UPDATE places p
SET category_id = t.id
FROM categories o
         LEFT JOIN categories t
                   ON t.household_id = $2
                       AND t.builtin_key = o.builtin_key
WHERE p.household_id = $1
  AND p.category_id = o.id
  AND o.builtin_key IS NOT NULL
`

type RemapBuiltinCategoriesParams struct {
	FromHouseholdID uuid.UUID
	ToHouseholdID   uuid.UUID
}

func (q *Queries) RemapBuiltinCategories(ctx context.Context, arg RemapBuiltinCategoriesParams) error {
	_, err := q.db.Exec(ctx, remapBuiltinCategories, arg.FromHouseholdID, arg.ToHouseholdID)
	return err
}

const setHouseholdPlan = `-- name: SetHouseholdPlan :execrows
UPDATE households
SET plan = $2
WHERE id = $1
  AND plan <> $2
`

type SetHouseholdPlanParams struct {
	ID   uuid.UUID
	Plan string
}

func (q *Queries) SetHouseholdPlan(ctx context.Context, arg SetHouseholdPlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHouseholdPlan, arg.ID, arg.Plan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
