// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"
	"uuid"

	"github.com/mickamy/LocateDo/internal/feature/todo/model"
	todov1 "github.com/mickamy/LocateDo/internal/gen/locatedo/todo/v1"
)

// TodoFromTodoInput maps *todov1.TodoInput to model.Todo.
func TodoFromTodoInput(src *todov1.TodoInput) (model.Todo, error) {
	if src == nil {
		return model.Todo{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.Todo{}, fmt.Errorf("map model.Todo.ID: %w", err0)
	}
	v3, err2 := uuid.Parse(src.GetPlaceId())
	if err2 != nil {
		return model.Todo{}, fmt.Errorf("map model.Todo.PlaceID: %w", err2)
	}
	var v4 *uuid.UUID
	if v5 := src.AssigneeId; v5 != nil {
		var v6 uuid.UUID
		v8, err7 := uuid.Parse(*v5)
		if err7 != nil {
			return model.Todo{}, fmt.Errorf("map model.Todo.AssigneeID: %w", err7)
		}
		v6 = v8
		v4 = &v6
	}
	return model.Todo{
		ID:         v1,
		PlaceID:    v3,
		Title:      src.GetTitle(),
		Trigger:    TriggerFromTodov1(src.GetTrigger()),
		AssigneeID: v4,
	}, nil
}
