// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"
	"uuid"

	"github.com/mickamy/LocateDo/internal/feature/todo/model"
	todov1 "github.com/mickamy/LocateDo/internal/gen/locatedo/todo/v1"
)

// TodoFromTodoInput maps *todov1.TodoInput to model.Todo.
func TodoFromTodoInput(src *todov1.TodoInput) (model.Todo, error) {
	if src == nil {
		return model.Todo{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.Todo{}, fmt.Errorf("map model.Todo.ID: %w", err0)
	}
	v3, err2 := uuid.Parse(src.GetPlaceId())
	if err2 != nil {
		return model.Todo{}, fmt.Errorf("map model.Todo.PlaceID: %w", err2)
	}
	v5, err4 := TriggerFromTodov1(src.GetTrigger())
	if err4 != nil {
		return model.Todo{}, fmt.Errorf("map model.Todo.Trigger: %w", err4)
	}
	var v6 *uuid.UUID
	if v7 := src.AssigneeId; v7 != nil {
		var v8 uuid.UUID
		v10, err9 := uuid.Parse(*v7)
		if err9 != nil {
			return model.Todo{}, fmt.Errorf("map model.Todo.AssigneeID: %w", err9)
		}
		v8 = v10
		v6 = &v8
	}
	return model.Todo{
		ID:         v1,
		PlaceID:    v3,
		Title:      src.GetTitle(),
		Trigger:    v5,
		AssigneeID: v6,
	}, nil
}
