// Code generated by kanna. DO NOT EDIT.

package interceptor

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/household/repository"
)

// NewInterceptors initializes dependencies and constructs Interceptors.
func NewInterceptors(config di.Config, infra di.Infra, lib di.Lib) Interceptors {
	app := config.App
	signer := lib.Signer
	reader := infra.Reader
	memberships := repository.NewMembership(reader)

	return Interceptors{
		app:         app,
		signer:      signer,
		memberships: memberships,
	}
}
