// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"github.com/mickamy/LocateDo/internal/feature/account/model"
	accountv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/account/v1"
	"github.com/mickamy/LocateDo/internal/lib/converters"
)

// SessionToAccountv1 maps model.Session to *accountv1.Session.
func SessionToAccountv1(src model.Session) *accountv1.Session {
	return &accountv1.Session{
		UserId:               converters.UUIDToString(src.UserID),
		AccessToken:          src.AccessToken,
		AccessTokenExpiresAt: converters.TimeToTimestamp(src.AccessTokenExpiresAt),
		RefreshToken:         src.RefreshToken,
		NewUser:              src.NewUser,
	}
}
