// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: place_queries.sql

package queries

import (
	"context"

	"uuid"
)

const countPlaces = `-- name: CountPlaces :one
SELECT count(*)
FROM places
WHERE household_id = $1
`

func (q *Queries) CountPlaces(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaces, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlace = `-- name: DeletePlace :exec
DELETE
FROM places
WHERE id = $1
  AND household_id = $2
`

type DeletePlaceParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) DeletePlace(ctx context.Context, arg DeletePlaceParams) error {
	_, err := q.db.Exec(ctx, deletePlace, arg.ID, arg.HouseholdID)
	return err
}

const placeExists = `-- name: PlaceExists :one
SELECT EXISTS (SELECT 1
               FROM places
               WHERE id = $1
                 AND household_id = $2)
`

type PlaceExistsParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) PlaceExists(ctx context.Context, arg PlaceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, placeExists, arg.ID, arg.HouseholdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPlace = `-- name: UpsertPlace :exec
INSERT INTO places (id, household_id, name, lat, lng, radius_m, category_id, sort_order)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        (SELECT c.id
         FROM categories c
         WHERE c.id = $7
           AND c.household_id = $2),
        $8)
ON CONFLICT (id, household_id) DO UPDATE
    SET name        = EXCLUDED.name,
        lat         = EXCLUDED.lat,
        lng         = EXCLUDED.lng,
        radius_m    = EXCLUDED.radius_m,
        category_id = EXCLUDED.category_id,
        sort_order  = EXCLUDED.sort_order
`

type UpsertPlaceParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	Lat         float64
	Lng         float64
	RadiusM     int32
	CategoryID  *uuid.UUID
	SortOrder   int32
}

// A category id the household does not have resolves to NULL.
func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) error {
	_, err := q.db.Exec(ctx, upsertPlace,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.RadiusM,
		arg.CategoryID,
		arg.SortOrder,
	)
	return err
}
