// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"
	"uuid"

	"github.com/mickamy/LocateDo/internal/feature/category/model"
	categoryv1 "github.com/mickamy/LocateDo/internal/gen/locatedo/category/v1"
)

// CategoryFromCategoryInput maps *categoryv1.CategoryInput to model.Category.
func CategoryFromCategoryInput(src *categoryv1.CategoryInput) (model.Category, error) {
	if src == nil {
		return model.Category{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.Category{}, fmt.Errorf("map model.Category.ID: %w", err0)
	}
	return model.Category{
		ID:         v1,
		BuiltinKey: BuiltinCategoryToKey(src.GetBuiltin()),
		Name:       src.Name,
		Icon:       src.GetIcon(),
		Color:      src.GetColor(),
		SortOrder:  src.GetSortOrder(),
	}, nil
}
