// Generated by tools/analytics/catalog from shared/analytics/catalog.yaml. Do not edit.

nonisolated enum AnalyticsEvent: String {
    case alwaysPromptAnswered = "always_prompt_answered"
    case analyticsConsentGranted = "analytics_consent_granted"
    case campaignOpened = "campaign_opened"
    case completionNoticeOpened = "completion_notice_opened"
    case completionNoticesChanged = "completion_notices_changed"
    case dailyState = "daily_state"
    case inviteAccepted = "invite_accepted"
    case limitReached = "limit_reached"
    case locationAuthChanged = "location_auth_changed"
    case notificationAuthChanged = "notification_auth_changed"
    case onboardingCompleted = "onboarding_completed"
    case paywallDismissed = "paywall_dismissed"
    case paywallPurchased = "paywall_purchased"
    case paywallShown = "paywall_shown"
    case permissionActionTapped = "permission_action_tapped"
    case permissionBannerTapped = "permission_banner_tapped"
    case placeAdded = "place_added"
    case placeDeleted = "place_deleted"
    case placeDuplicatePrompted = "place_duplicate_prompted"
    case promotionsConsentChanged = "promotions_consent_changed"
    case promotionsPromptAnswered = "promotions_prompt_answered"
    case promotionsPromptShown = "promotions_prompt_shown"
    case purchaseCanceled = "purchase_canceled"
    case purchaseFailed = "purchase_failed"
    case purchaseStarted = "purchase_started"
    case reminderNotified = "reminder_notified"
    case reminderOpened = "reminder_opened"
    case reminderSuppressed = "reminder_suppressed"
    case restoreCompleted = "restore_completed"
    case shareTapped = "share_tapped"
    case todoAdded = "todo_added"
    case todoCompleted = "todo_completed"
    case todoDeleteUndone = "todo_delete_undone"
    case todoDeleted = "todo_deleted"
    case todoTriggerChanged = "todo_trigger_changed"
}

nonisolated enum AnalyticsParameter: String {
    case action
    case ageDays = "age_days"
    case ageHours = "age_hours"
    case assigned
    case campaignID = "campaign_id"
    case category
    case choice
    case completedTodoCount7d = "completed_todo_count_7d"
    case count
    case customCategoryCount = "custom_category_count"
    case daysSinceInstall = "days_since_install"
    case durationS = "duration_s"
    case entry
    case from
    case hasURL = "has_url"
    case householdMembers = "household_members"
    case kind
    case latencyS = "latency_s"
    case locationAuth = "location_auth"
    case missing
    case mode
    case notificationAuth = "notification_auth"
    case openDepartureTodos = "open_departure_todos"
    case openTodoCount = "open_todo_count"
    case openTodos = "open_todos"
    case placeChanged = "place_changed"
    case placeCount = "place_count"
    case placeEvent = "place_event"
    case placeOpenTodos = "place_open_todos"
    case placePreset = "place_preset"
    case placesWithOpenTodos = "places_with_open_todos"
    case plan
    case preciseLocation = "precise_location"
    case promotionsConsent = "promotions_consent"
    case radiusM = "radius_m"
    case rank
    case reason
    case result
    case shownCount = "shown_count"
    case signedIn = "signed_in"
    case source
    case stayMin = "stay_min"
    case step
    case suggestedCategory = "suggested_category"
    case to
    case todoCount = "todo_count"
    case trigger
    case via
    case watchAppInstalled = "watch_app_installed"
}

nonisolated enum AnalyticsUserProperty: String {
    case appBuild = "app_build"
    case householdMembers = "household_members"
    case locationAuth = "location_auth"
    case openTodoCount = "open_todo_count"
    case placeCount = "place_count"
    case plan
    case promotionsConsent = "promotions_consent"
    case signedIn = "signed_in"
}

nonisolated enum AnalyticsScreen: String {
    case acceptInvite = "accept_invite"
    case account
    case accountBenefits = "account_benefits"
    case alwaysLocationPrompt = "always_location_prompt"
    case categories
    case categoryEditor = "category_editor"
    case home
    case map
    case onboarding
    case paywall
    case placeDetail = "place_detail"
    case placeEditor = "place_editor"
    case placePicker = "place_picker"
    case settings
    case sharing
    case sharingIntro = "sharing_intro"
    case todoEditor = "todo_editor"
    case todos
    case updateRequired = "update_required"
}

nonisolated enum ScreenEntry: String {
    case allTodos = "all_todos"
    case allTodosEmpty = "all_todos_empty"
    case completionNotice = "completion_notice"
    case duplicatePrompt = "duplicate_prompt"
    case home
    case homeEmpty = "home_empty"
    case homeList = "home_list"
    case homeMenu = "home_menu"
    case mapPin = "map_pin"
    case newPlace = "new_place"
    case notification
    case onboarding
    case permissionBanner = "permission_banner"
    case place
    case todoEditor = "todo_editor"
}
