package android

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/mickamy/LocateDo/tools/l10n/internal/analyze"
	"github.com/mickamy/LocateDo/tools/l10n/internal/locale"
	"github.com/mickamy/LocateDo/tools/l10n/internal/template"
)

const (
	header = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
		"<!-- Generated by tools/l10n from shared/strings. Do not edit. -->\n"
	indent = "    "
)

// Generate returns one strings.xml per language, keyed by its path under the res directory.
func Generate(m analyze.Model) map[string][]byte {
	out := make(map[string][]byte, len(m.Langs))
	for _, lang := range m.Langs {
		out[valuesDir(lang, m.DefaultLang)+"/strings.xml"] = generate(m, lang)
	}
	return out
}

func generate(m analyze.Model, lang string) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("<resources>\n")
	for _, msg := range m.Messages {
		if !m.Meta.Includes(msg.Key, locale.PlatformAndroid) {
			continue
		}
		e, ok := msg.Translations[lang]
		if !ok {
			continue
		}
		if lang == m.DefaultLang {
			if comment := m.Meta.Comment(msg.Key); comment != "" {
				fmt.Fprintf(&b, "%s<!-- %s -->\n", indent, strings.ReplaceAll(comment, "--", "- -"))
			}
		}
		name := analyze.AndroidResourceName(msg.Key)
		if msg.Plural {
			writePlurals(&b, name, msg, e)
		} else {
			writeString(&b, name, msg, e.Single)
		}
	}
	b.WriteString("</resources>\n")
	return b.Bytes()
}

func writeString(b *bytes.Buffer, name string, msg analyze.Message, tmpl template.Template) {
	value := render(msg, tmpl)
	attrs := ""
	if len(msg.Params) == 0 && strings.Contains(value, "%") {
		attrs = ` formatted="false"`
	}
	fmt.Fprintf(b, "%s<string name=\"%s\"%s>%s</string>\n", indent, name, attrs, value)
}

func writePlurals(b *bytes.Buffer, name string, msg analyze.Message, e locale.Entry) {
	fmt.Fprintf(b, "%s<plurals name=\"%s\">\n", indent, name)
	for _, category := range locale.PluralCategories {
		tmpl, ok := e.Plural[category]
		if !ok {
			continue
		}
		fmt.Fprintf(b, "%s%s<item quantity=\"%s\">%s</item>\n", indent, indent, category, render(msg, tmpl))
	}
	fmt.Fprintf(b, "%s</plurals>\n", indent)
}

func render(msg analyze.Message, tmpl template.Template) string {
	formatted := len(msg.Params) > 0
	var b strings.Builder
	for _, seg := range tmpl.Segments() {
		if seg.Param == "" {
			text := escape(seg.Text)
			if formatted {
				text = strings.ReplaceAll(text, "%", "%%")
			}
			b.WriteString(text)
			continue
		}
		pos, kind := msg.Placeholder(seg.Param)
		fmt.Fprintf(&b, "%%%d$%s", pos, specifier(kind))
	}
	return guard(b.String())
}

func specifier(kind template.Kind) string {
	if kind == template.KindInt {
		return "d"
	}
	return "s"
}

// guard keeps the value as written: a leading @ or ? would otherwise be read as a resource reference,
// and surrounding whitespace would be trimmed.
func guard(value string) string {
	if strings.HasPrefix(value, "@") || strings.HasPrefix(value, "?") {
		return `\` + value
	}
	if value != strings.TrimSpace(value) {
		return `"` + value + `"`
	}
	return value
}

func escape(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '&':
			b.WriteString("&amp;")
		case '<':
			b.WriteString("&lt;")
		case '>':
			b.WriteString("&gt;")
		case '"':
			b.WriteString(`\"`)
		case '\'':
			b.WriteString(`\'`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

func valuesDir(lang, defaultLang string) string {
	if lang == defaultLang {
		return "values"
	}
	parts := strings.Split(lang, "-")
	switch {
	case len(parts) == 1:
		return "values-" + parts[0]
	case len(parts) == 2 && len(parts[1]) == 2:
		return "values-" + parts[0] + "-r" + strings.ToUpper(parts[1])
	default:
		return "values-b+" + strings.Join(parts, "+")
	}
}
