name: server-deploy-stg

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: stg

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Create .env file
        env:
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
          SEAL_KEY: ${{ secrets.SEAL_KEY }}
          APPLE_BUNDLE_ID: com.locatedo.LocateDo.stg
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_PRIVATE_KEY: ${{ secrets.APPLE_PRIVATE_KEY }}
          APNS_KEY_ID: ${{ secrets.APNS_KEY_ID }}
          APNS_PRIVATE_KEY: ${{ secrets.APNS_PRIVATE_KEY }}
          APNS_TOPIC: com.locatedo.LocateDo.stg
          APNS_ENVIRONMENT: production
          REVENUECAT_API_KEY: ${{ secrets.REVENUECAT_API_KEY }}
          REVENUECAT_PROJECT_ID: proj593408b8
          REVENUECAT_ENTITLEMENT_ID: entlf8b9ff89f9
          REVENUECAT_WEBHOOK_AUTH: ${{ secrets.REVENUECAT_WEBHOOK_AUTH }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          make -B -C server .env

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: server/go.mod
          cache-dependency-path: |
            server/go.sum
            server/tools/go.sum

      - name: Migrate database
        run: |
          make -C server db-migrate

      - name: Deploy Docker Compose
        run: |
          cd server
          docker compose -f compose.stg.yaml up -d --build
          docker image prune -f
