// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"uuid"
)

type Category struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BuiltinKey  *string
	Name        *string
	Icon        string
	Color       string
	SortOrder   int32
	UpdatedAt   time.Time
	Version     int64
}

type Place struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	Lat         float64
	Lng         float64
	RadiusM     int32
	CategoryID  *uuid.UUID
	SortOrder   int32
	UpdatedAt   time.Time
	Version     int64
}

type Todo struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	AssigneeID  *uuid.UUID
	CompletedAt *time.Time
	UpdatedAt   time.Time
	Version     int64
}
