// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_queries.sql

package queries

import (
	"context"
	"time"

	"uuid"
)

const listCategoryChanges = `-- name: ListCategoryChanges :many
SELECT id, household_id, builtin_key, name, icon, color, sort_order, updated_at, version
FROM categories
WHERE household_id = $1
  AND version > $2
ORDER BY version
LIMIT $3
`

type ListCategoryChangesParams struct {
	HouseholdID uuid.UUID
	Version     int64
	Limit       int32
}

func (q *Queries) ListCategoryChanges(ctx context.Context, arg ListCategoryChangesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoryChanges, arg.HouseholdID, arg.Version, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.BuiltinKey,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.SortOrder,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletions = `-- name: ListDeletions :many
SELECT table_name, row_id, version
FROM deletions
WHERE household_id = $1
  AND version > $2
ORDER BY version
LIMIT $3
`

type ListDeletionsParams struct {
	HouseholdID uuid.UUID
	Version     int64
	Limit       int32
}

type ListDeletionsRow struct {
	TableName string
	RowID     uuid.UUID
	Version   int64
}

func (q *Queries) ListDeletions(ctx context.Context, arg ListDeletionsParams) ([]ListDeletionsRow, error) {
	rows, err := q.db.Query(ctx, listDeletions, arg.HouseholdID, arg.Version, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletionsRow
	for rows.Next() {
		var i ListDeletionsRow
		if err := rows.Scan(&i.TableName, &i.RowID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipChanges = `-- name: ListMembershipChanges :many
SELECT m.household_id, m.user_id, m.role, u.display_name, m.joined_at, m.updated_at, m.version
FROM memberships m
         JOIN users u ON u.id = m.user_id
WHERE m.household_id = $1
  AND m.version > $2
ORDER BY m.version
LIMIT $3
`

type ListMembershipChangesParams struct {
	HouseholdID uuid.UUID
	Version     int64
	Limit       int32
}

type ListMembershipChangesRow struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
	DisplayName string
	JoinedAt    time.Time
	UpdatedAt   time.Time
	Version     int64
}

func (q *Queries) ListMembershipChanges(ctx context.Context, arg ListMembershipChangesParams) ([]ListMembershipChangesRow, error) {
	rows, err := q.db.Query(ctx, listMembershipChanges, arg.HouseholdID, arg.Version, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipChangesRow
	for rows.Next() {
		var i ListMembershipChangesRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.DisplayName,
			&i.JoinedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceChanges = `-- name: ListPlaceChanges :many
SELECT id, household_id, name, lat, lng, radius_m, category_id, sort_order, updated_at, version
FROM places
WHERE household_id = $1
  AND version > $2
ORDER BY version
LIMIT $3
`

type ListPlaceChangesParams struct {
	HouseholdID uuid.UUID
	Version     int64
	Limit       int32
}

func (q *Queries) ListPlaceChanges(ctx context.Context, arg ListPlaceChangesParams) ([]Place, error) {
	rows, err := q.db.Query(ctx, listPlaceChanges, arg.HouseholdID, arg.Version, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.RadiusM,
			&i.CategoryID,
			&i.SortOrder,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoChanges = `-- name: ListTodoChanges :many
SELECT t.id,
       t.household_id,
       t.place_id,
       t.title,
       t.assignee_id,
       t.creator_id,
       c.completer_id,
       t.completed_at,
       t.updated_at,
       t.version
FROM todos t
         LEFT JOIN LATERAL (SELECT tc.completer_id
                            FROM todo_completions tc
                            WHERE tc.todo_id = t.id
                              AND tc.reopened_at IS NULL
                            ORDER BY tc.id DESC
                            LIMIT 1) c ON true
WHERE t.household_id = $1
  AND t.version > $2
ORDER BY t.version
LIMIT $3
`

type ListTodoChangesParams struct {
	HouseholdID uuid.UUID
	Version     int64
	Limit       int32
}

type ListTodoChangesRow struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	PlaceID     uuid.UUID
	Title       string
	AssigneeID  *uuid.UUID
	CreatorID   *uuid.UUID
	CompleterID *uuid.UUID
	CompletedAt *time.Time
	UpdatedAt   time.Time
	Version     int64
}

// The completer is the one of the latest completion not reopened.
func (q *Queries) ListTodoChanges(ctx context.Context, arg ListTodoChangesParams) ([]ListTodoChangesRow, error) {
	rows, err := q.db.Query(ctx, listTodoChanges, arg.HouseholdID, arg.Version, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoChangesRow
	for rows.Next() {
		var i ListTodoChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.PlaceID,
			&i.Title,
			&i.AssigneeID,
			&i.CreatorID,
			&i.CompleterID,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseSweptVersion = `-- name: RaiseSweptVersion :exec
UPDATE households
SET swept_version = GREATEST(swept_version, $1)
WHERE id = $2
`

type RaiseSweptVersionParams struct {
	Version int64
	ID      uuid.UUID
}

func (q *Queries) RaiseSweptVersion(ctx context.Context, arg RaiseSweptVersionParams) error {
	_, err := q.db.Exec(ctx, raiseSweptVersion, arg.Version, arg.ID)
	return err
}

const sweepDeletions = `-- name: SweepDeletions :many
DELETE
FROM deletions
WHERE deleted_at < $1
RETURNING household_id, version
`

type SweepDeletionsRow struct {
	HouseholdID uuid.UUID
	Version     int64
}

func (q *Queries) SweepDeletions(ctx context.Context, deletedAt time.Time) ([]SweepDeletionsRow, error) {
	rows, err := q.db.Query(ctx, sweepDeletions, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepDeletionsRow
	for rows.Next() {
		var i SweepDeletionsRow
		if err := rows.Scan(&i.HouseholdID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
