// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/repository"
	repository3 "github.com/mickamy/LocateDo/internal/feature/device/repository"
	repository2 "github.com/mickamy/LocateDo/internal/feature/household/repository"
	"github.com/mickamy/LocateDo/internal/outbox"
)

// NewDeleteAccount initializes dependencies and constructs DeleteAccount.
func NewDeleteAccount(infra di.Infra) *DeleteAccount {
	transactor := infra.Transactor
	reader := infra.Reader
	users := repository.NewUser(reader)
	appleTokens := repository.NewAppleToken(reader)
	messages := outbox.NewRepository(reader)

	return &DeleteAccount{
		transactor:  transactor,
		users:       users,
		appleTokens: appleTokens,
		messages:    messages,
	}
}

// NewRefreshToken initializes dependencies and constructs RefreshToken.
func NewRefreshToken(infra di.Infra, lib di.Lib) *RefreshToken {
	transactor := infra.Transactor
	reader := infra.Reader
	tokens := repository.NewRefreshToken(reader)
	memberships := repository2.NewMembership(reader)
	signer := lib.Signer

	return &RefreshToken{
		transactor:  transactor,
		tokens:      tokens,
		memberships: memberships,
		signer:      signer,
	}
}

// NewSignInWithApple initializes dependencies and constructs SignInWithApple.
func NewSignInWithApple(infra di.Infra, lib di.Lib) *SignInWithApple {
	transactor := infra.Transactor
	reader := infra.Reader
	users := repository.NewUser(reader)
	tokens := repository.NewRefreshToken(reader)
	memberships := repository2.NewMembership(reader)
	appleTokens := repository.NewAppleToken(reader)
	apple := infra.Apple
	signer := lib.Signer
	box := lib.Box

	return &SignInWithApple{
		transactor:  transactor,
		users:       users,
		tokens:      tokens,
		memberships: memberships,
		appleTokens: appleTokens,
		apple:       apple,
		signer:      signer,
		box:         box,
	}
}

// NewSignInWithGoogle initializes dependencies and constructs SignInWithGoogle.
func NewSignInWithGoogle(infra di.Infra, lib di.Lib) *SignInWithGoogle {
	transactor := infra.Transactor
	reader := infra.Reader
	users := repository.NewUser(reader)
	tokens := repository.NewRefreshToken(reader)
	memberships := repository2.NewMembership(reader)
	google := infra.Google
	signer := lib.Signer

	return &SignInWithGoogle{
		transactor:  transactor,
		users:       users,
		tokens:      tokens,
		memberships: memberships,
		google:      google,
		signer:      signer,
	}
}

// NewSignOut initializes dependencies and constructs SignOut.
func NewSignOut(infra di.Infra) *SignOut {
	transactor := infra.Transactor
	reader := infra.Reader
	tokens := repository.NewRefreshToken(reader)
	devices := repository3.NewDevice(reader)

	return &SignOut{
		transactor: transactor,
		tokens:     tokens,
		devices:    devices,
	}
}
