// Code generated by kanna. DO NOT EDIT.

package usecase

import (
	"github.com/mickamy/LocateDo/internal/di"
	"github.com/mickamy/LocateDo/internal/feature/account/repository"
)

// NewDeleteAccount initializes dependencies and constructs DeleteAccount.
func NewDeleteAccount(infra di.Infra, lib di.Lib) *DeleteAccount {
	transactor := infra.Transactor
	reader := infra.Reader
	users := repository.NewUser(reader)
	appleTokens := repository.NewAppleToken(reader)
	apple := infra.Apple
	box := lib.Box

	return &DeleteAccount{
		transactor:  transactor,
		users:       users,
		appleTokens: appleTokens,
		apple:       apple,
		box:         box,
	}
}

// NewRefreshToken initializes dependencies and constructs RefreshToken.
func NewRefreshToken(infra di.Infra, lib di.Lib) *RefreshToken {
	transactor := infra.Transactor
	reader := infra.Reader
	tokens := repository.NewRefreshToken(reader)
	signer := lib.Signer

	return &RefreshToken{
		transactor: transactor,
		tokens:     tokens,
		signer:     signer,
	}
}

// NewSignInWithApple initializes dependencies and constructs SignInWithApple.
func NewSignInWithApple(infra di.Infra, lib di.Lib) *SignInWithApple {
	transactor := infra.Transactor
	reader := infra.Reader
	users := repository.NewUser(reader)
	tokens := repository.NewRefreshToken(reader)
	appleTokens := repository.NewAppleToken(reader)
	apple := infra.Apple
	signer := lib.Signer
	box := lib.Box

	return &SignInWithApple{
		transactor:  transactor,
		users:       users,
		tokens:      tokens,
		appleTokens: appleTokens,
		apple:       apple,
		signer:      signer,
		box:         box,
	}
}
